### ISSUE TITLE
Support Rockchip ARM CPUs

### ISSUE THREAD

**Issue by seansackowitz** [Picovoice/porcupine#1016]
### Expected behaviour
Porcupine to function at all, and support Rockchip aarch64

### Actual behaviour
```
$ python3 -m pvporcupine
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.10/dist-packages/pvporcupine/__init__.py", line 12, in <module>
    from ._factory import *
  File "/usr/local/lib/python3.10/dist-packages/pvporcupine/_factory.py", line 15, in <module>
    from ._util import *
  File "/usr/local/lib/python3.10/dist-packages/pvporcupine/_util.py", line 76, in <module>
    _PV_SYSTEM, _PV_MACHINE = _pv_platform()
  File "/usr/local/lib/python3.10/dist-packages/pvporcupine/_util.py", line 69, in _pv_platform
    pv_machine = _pv_linux_machine(platform.machine())
  File "/usr/local/lib/python3.10/dist-packages/pvporcupine/_util.py", line 60, in _pv_linux_machine
    raise NotImplementedError("Unsupported CPU: '%s'." % cpu_part)
NotImplementedError: Unsupported CPU: '0xd05'.
```

### Steps to reproduce the behaviour
I am using an Orangepi 5B with a Rockchip RK3588S CPU, which reports itself as a standard aarch64 processor
```
$ uname -a
Linux ubuntu 5.10.160-rockchip #3 SMP Thu Jun 15 01:13:53 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
```
When attempting to use porcupine, I get the error above
```
pip3 install pvporcupine
python3 -m pvporcupine (Or any python script that imports it)
```

**Comment by kenarsa** [comment]
We don't plan to support Rockchip unless an enterprise customer asks for it.

**Comment by ssssssssssshuai** [comment]
您好，您的这个问题解决了吗？方便交流一下？
