### ISSUE TITLE
Porcupine Issue: INVALID_ARGUMENT in python with model_path

### ISSUE THREAD

**Issue by efschu** [Picovoice/porcupine#1045]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
it starts

### Actual behaviour

when i create the pvporcupine object with `model_path` it failes - without `model_path` and `keywords` instead of `keyword_paths` it works
Downloaded porcupine_params_de.pv from here:
https://github.com/Picovoice/porcupine/blob/master/lib/common/porcupine_params_de.pv

```
[ERROR] loading parameters failed with `INVALID_ARGUMENT`
Traceback (most recent call last):
  File "/home/efeu/porcupine/porcupine_mqtt.py", line 21, in <module>
    handle = pvporcupine.create(access_key=access_key, keyword_paths=keyword_paths, model_path=model_path, library_path=library_path)
  File "/usr/local/lib/python3.9/dist-packages/pvporcupine/_factory.py", line 69, in create
    return Porcupine(
  File "/usr/local/lib/python3.9/dist-packages/pvporcupine/_porcupine.py", line 164, in __init__
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]()
pvporcupine._porcupine.PorcupineInvalidArgumentError
```
### Steps to reproduce the behaviour
Hardware: raspi 4
OS: raspian bullseye
Kernel: Linux raspberrypi 6.1.21-v8+
python 3.9.2
pvporcupine-2.2.1

Code:

```
import argparse
import os
import struct
import wave
from datetime import datetime

import pvporcupine
from pvrecorder import PvRecorder


# AccessKey obtained from Picovoice Console (https://console.picovoice.ai/)
access_key = "<< my working key >>"
keyword_paths=["/home/efeu/porcupine/Hokuspokus_de_raspberry-pi_v2_2_0.ppn"]
library_path="/usr/local/lib/python3.9/dist-packages/pvporcupine/lib/raspberry-pi/cortex-a72-aarch64/libpv_porcupine.so"
model_path="/usr/local/lib/python3.9/dist-packages/pvporcupine/lib/common/porcupine_params_de.pv"

#for i, device in enumerate(PvRecorder.get_available_devices()):
#    print('Device %d: %s' % (i, device))

#handle = pvporcupine.create(access_key=access_key, keywords=['porcupine'])
handle = pvporcupine.create(access_key=access_key, keyword_paths=keyword_paths, model_path=model_path, library_path=library_path)

recorder = PvRecorder(
    frame_length=handle.frame_length,
    #device_index=args.audio_device_index)
    device_index=9)
recorder.start()

while True:
    pcm = recorder.read()
    result = handle.process(pcm)

    if result >= 0:
        print('Detected')
```

**Comment by efschu** [comment]
Nevermind. My porcupine_params_de.pv was corrupted.
