### ISSUE TITLE
Porcupine Issue: Node.js A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by Johonnyy** [Picovoice/porcupine#1069]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
It works and initializes like normal

### Actual behaviour
When I try to initialize Porcupine in node.js like this:
`let handle = new Porcupine(
	porcupineAccessKey,
	["./wake_words/hey-amber_en_wasm_v2_2_0.ppn"],
	[0.5]
);`
I get the DLL error
`Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\johnn\Documents\Projects\amber\frontend\node_modules\@picovoice\porcupine-node\lib\windows\amd64\pv_porcupine.node
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1354:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:1822)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at new Porcupine (C:\Users\johnn\Documents\Projects\amber\frontend\node_modules\@picovoice\porcupine-node\dist\porcupine.js:89:29)       
    at Object.<anonymous> (C:\Users\johnn\Documents\Projects\amber\frontend\porcupine.js:5:14)`

### Steps to reproduce the behaviour
install @picovoice/porcupine-node on npm
follow the quick start: https://picovoice.ai/docs/quick-start/porcupine-nodejs/
it will fail at the `new Porcupine` part (for me atleast)

(Include enough details so that the issue can be reproduced independently.)

**Comment by mrrostam** [comment]
I am unable to replicate the problem on my system (Windows 11, Node.js 18). Could you please provide detailed specifications of the machine where you are attempting to run Porcupine? This includes information about the Node.js version and Windows version.

Additionally, could you try running our [node demo]( https://github.com/Picovoice/porcupine/tree/master/demo/nodejs) and see if you encounter the same issue?

**Comment by mrrostam** [comment]
The Node.js SDK is specifically designed to run within the Node environment. For Electron, you need to use our [web binding](https://github.com/Picovoice/porcupine/tree/master/binding/web)
