### ISSUE TITLE
porcupine.py: tilde char not expanded with multiple keyword files 

### ISSUE THREAD

**Issue by torntrousers** [Picovoice/Porcupine#107]
Running on a Mac, if i do ```python demo/python/porcupine_demo.py --keyword_file_paths ~/Development/porcupine/play\ daft\ punk_mac.ppn,~/Development/porcupine/play\ pink\ floyd_mac.ppn```
then it fails with
```
listening for:
- play daft punk (sensitivity: 0.500000)
- play pink floyd (sensitivity: 0.500000)
Traceback (most recent call last):
  File "demo/python/porcupine_demo.py", line 225, in <module>
    input_device_index=args.input_audio_device_index).run()
  File "demo/python/porcupine_demo.py", line 103, in run
    sensitivities=self._sensitivities)
  File "demo/python/../../binding/python/porcupine.py", line 88, in __init__
    raise IOError("Could not find keyword file at '%s'" % x)
OSError: Could not find keyword file at '~/Development/porcupine/play pink floyd_mac.ppn'
```
I changed it like this and now it works:
```
git diff binding/python/porcupine.py
diff --git a/binding/python/porcupine.py b/binding/python/porcupine.py
index 12e058e..a19e421 100644
--- a/binding/python/porcupine.py
+++ b/binding/python/porcupine.py
@@ -84,7 +84,7 @@ class Porcupine(object):
                 raise ValueError("Different number of sensitivity and keyword file path parameters are provided.")

             for x in keyword_file_paths:
-                if not os.path.exists(x):
+                if not os.path.exists(os.path.expanduser(x)):
                     raise IOError("Could not find keyword file at '%s'" % x)

             for x in sensitivities:
@@ -109,7 +109,7 @@ class Porcupine(object):
         status = init_func(
             model_file_path.encode(),
             self._num_keywords,
-            (c_char_p * self._num_keywords)(*[x.encode() for x in keyword_file_paths]),
+            (c_char_p * self._num_keywords)(*[os.path.expanduser(x).encode() for x in keyword_file_paths]),
             (c_float * self._num_keywords)(*sensitivities),
             byref(self._handle))
         if status is not self.PicovoiceStatuses.SUCCESS:
```

**Comment by kenarsa** [comment]
Perfect. This should work on Linux as well. Not sure about the behavior on a Windows machine. Feel free to submit a PR and I'll be happy to merge it in. Thanks!
