### ISSUE TITLE
Android demo crashes on Windows

### ISSUE THREAD

**Issue by juliendev20** [Picovoice/Porcupine#112]
### Expected behavior
Android demo works...

### Actual behavior
I have a crash on Android demo application. When I click on the "Start" button the app crashed. After having accepted the android permission.

### Steps to reproduce the behavior
I'm running the Android demo on Windows 10 64bits with the following output :

`2018-10-30 22:52:02.811 5105-5105/ai.picovoice.porcupine.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ai.picovoice.porcupine.demo, PID: 5105
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/ai.picovoice.porcupine.demo-Wntkwp8IOsNE2tM1mG4VeA==/base.apk", zip file "/data/app/ai.picovoice.porcupine.demo-Wntkwp8IOsNE2tM1mG4VeA==/split_lib_dependencies_apk.apk", zip file "/data/app/ai.picovoice.porcupine.demo-Wntkwp8IOsNE2tM1mG4VeA==/split_lib_resources_apk.apk", zip file "/data/app/ai.picovoice.porcupine.demo-Wntkwp8IOsNE2tM1mG4VeA==/split_lib_slice_0_apk.apk", zip file "/data/app/ai.picovoice.porcupine.demo-Wntkwp8IOsNE2tM1mG4VeA==/split_lib_slice_1_apk.apk", zip file "/data/app/ai.picovoice.porcupine.demo-Wntkwp8IOsNE2tM1mG4VeA==/split_lib_slice_2_apk.apk", zip file "/data/app/ai.picovoice.porcupine.demo-Wntkwp8IOsNE2tM1mG4VeA==/split_lib_slice_3_apk.apk", zip file "/data/app/ai.picovoice.porcupine.demo-Wntkwp8IOsNE2tM1mG4VeA==/split_lib_slice_4_apk.apk", zip file "/data/app/ai.picovoice.porcupine.demo-Wntkwp8IOsNE2tM1mG4VeA==/split_lib_slice_5_apk.apk", zip file "/data/app/ai.picovoice.porcupine.demo-Wntkwp8IOsNE2tM1mG4VeA==/split_lib_slice_6_apk.apk", zip file "/data/app/ai.picovoice.porcupine.demo-Wntkwp8IOsNE2tM1mG4VeA==/split_lib_slice_7_apk.apk", zip file "/data/app/ai.picovoice.porcupine.demo-Wntkwp8IOsNE2tM1mG4VeA==/split_lib_slice_8_apk.apk", zip file "/data/app/ai.picovoice.porcupine.demo-Wntkwp8IOsNE2tM1mG4VeA==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/ai.picovoice.porcupine.demo-Wntkwp8IOsNE2tM1mG4VeA==/lib/arm64, /system/lib64, /system/vendor/lib64]]] couldn't find "libpv_porcupine.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at ai.picovoice.porcupine.Porcupine.<clinit>(Porcupine.java:28)
        at ai.picovoice.porcupinemanager.PorcupineManager.<init>(PorcupineManager.java:95)
        at ai.picovoice.porcupine.demo.MainActivity.initPorcupine(MainActivity.java:104)
        at ai.picovoice.porcupine.demo.MainActivity.onRequestPermissionsResult(MainActivity.java:151)
        at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7737)
        at android.app.Activity.dispatchActivityResult(Activity.java:7560)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4487)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4534)
        at android.app.ActivityThread.-wrap20(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1752)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)`

(I tried to build the project from Mac OS. I don't have this issues.)

**Comment by kenarsa** [comment]
Based on what you've sent it seems like the init has failed. One thing that we know not working on Windows is that the keyword files are not copied properly as they are symlinks. I suspect that is the issue. Try to copy them yourself. Also look into logcat there is more information there from C library.

**Comment by kenarsa** [comment]
closing due to inactivity. Please reopen if problem still exists ...
