### ISSUE TITLE
Porcupine Issue: Picovoice Error (00000136)

### ISSUE THREAD

**Issue by MiskaWasTaken** [Picovoice/porcupine#1201]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Porcupine docs
- [X] I have searched the existing issues for Porcupine

### SDK

Python

### Porcupine package version

3.0.1

### Framework version

Python 3.11.1

### Platform

Raspberry Pi

### OS/Browser version

Raspian OS (Bookworm)

### Describe the bug

aarya@raspberrypi:~ $ porcupine_demo_mic --access_key (access_key_here) --keywords picovoice --audio_device_index 1 --output_path ~/test.wav

AccessKey activation error
Traceback (most recent call last):
  File "/usr/local/bin/porcupine_demo_mic", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pvporcupinedemo/porcupine_demo_mic.py", line 100, in main
    raise e
  File "/usr/local/lib/python3.11/dist-packages/pvporcupinedemo/porcupine_demo_mic.py", line 88, in main
    porcupine = pvporcupine.create(
                ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pvporcupine/_factory.py", line 69, in create
    return Porcupine(
           ^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pvporcupine/_porcupine.py", line 198, in __init__
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status](
pvporcupine._porcupine.PorcupineActivationError: Initialization failed:
  [0] Picovoice Error (code `00000136`)
  [1] Picovoice Error (code `00000136`)
  [2] Picovoice Error (code `00000136`)
  [3] Picovoice Error (code `00000136`)
  
  
  This is what happens when i try to run the demo package 
  I have no idea how to fix this or whats happening 

### Steps To Reproduce

1. Open Raspbian OS on RPI 4B
2. pip install pvporcupinedemo
3. run porcupine_demo_mic --access_key (access_key_here) --keywords picovoice --audio_device_index 1 --output_path ~/test.wav
4. Error occurs

### Expected Behavior

For the demo to work

**Comment by ksyeo1010** [comment]
can you make sure internet is available on the device?

**Comment by MiskaWasTaken** [comment]
yes im positive internet is enabled im using ssh

**Comment by ksyeo1010** [comment]
can you mail your access key to `hello@picovoice.ai` and I can take a further look.

**Comment by laves** [comment]
Moved to email support

**Comment by hmq468674** [comment]
I have the same problem. How should I solve it?

**Comment by JDix90** [comment]
I am running into this same issue after downloading picovoice just yesterday to add to my pi.
