### ISSUE TITLE
Porcupine Issue: 

### ISSUE THREAD

**Issue by dzianisv** [Picovoice/porcupine#1211]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Porcupine docs
- [X] I have searched the existing issues for Porcupine

### SDK

Python

### Porcupine package version

lasest, installed by pip

### Framework version

lasest, installed by pip

### Platform

Raspberry Pi

### OS/Browser version

Armbian 23.11.1 Bookworm \l

### Describe the bug

Traceback (most recent call last):
  File "/opt/VoiceAssistant/./main.py", line 121, in <module>
    assistant = VoiceAssistant()
                ^^^^^^^^^^^^^^^^
  File "/opt/VoiceAssistant/./main.py", line 35, in __init__
    self.wakeword = WakeWord(lang=os.getenv("LANGUAGE", "ru"))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/VoiceAssistant/wakeword_pvporcupine.py", line 46, in __init__
    recognizer = pvporcupine.create(
                 ^^^^^^^^^^^^^^^^^^^
  File "/opt/VoiceAssistant/.venv/lib/python3.11/site-packages/pvporcupine/_factory.py", line 69, in create
    return Porcupine(
           ^^^^^^^^^^
  File "/opt/VoiceAssistant/.venv/lib/python3.11/site-packages/pvporcupine/_porcupine.py", line 198, in __init__
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status](
pvporcupine._porcupine.PorcupineActivationRefusedError: Initialization failed:
  [0] Picovoice Error (code `00000136`)
  [1] Picovoice Error (code `00000136`)
  [2] Picovoice Error (code `00000136`)

### Steps To Reproduce

https://github.com/dzianisv/VoiceAssistant/blob/main/src/wakeword_pvporcupine.py#L46

### Expected Behavior

👍

**Comment by mrrostam** [comment]
You're trying to use Porcupine on Armbian OS, but it's not officially supported. We only support the latest Raspberry Pi OS. Closing this issue, but feel free to reopen if you face the same problem on Raspberry Pi OS with [our demos](https://github.com/Picovoice/porcupine/tree/master/demo/python).
