### ISSUE TITLE
Porcupine Issue: Provided model (.pv) file belongs to a different version of the library

### ISSUE THREAD

**Issue by mikeglopez** [Picovoice/porcupine#1248]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Porcupine docs
- [X] I have searched the existing issues for Porcupine

### SDK

React

### Porcupine package version

3.0.3

### Framework version

Node v14.17.0

### Platform

Web (WASM)

### OS/Browser version

macOS 14.1

### Describe the bug

I'm getting this error:

picovoice error: PorcupineInvalidArgumentError: Initialization failed: 
  [0] Model (.pv) file belongs to a different version of the library. File is `2.2.0` while library is `3.0.0`.
  [1] Loading parameters failed with `INVALID_ARGUMENT`.
  [2] Picovoice Error (code `0000012C`)
    at pvStatusToException (index.js:3939:1)
    at worker.onmessage (index.js:4922:1)

### Steps To Reproduce

1. Train wake word and download provided keyword .ppn file (3.0 is stated in the downloaded file's name)
2. Download linked model .pv from picovoice github.
3. Use the provided commands to convert ppn and pv files to base64: 
- npx pvbase64 -i ${KEYWORD_FILE}.ppn -o ${KEYWORD_BASE64}.js -n ${KEYWORD_BASE64_VAR_NAME}
- npx pvbase64 -i ${PORCUPINE_PARAMS_PATH} -o ${OUTPUT_FILE_PATH}
5. Import base64 into variables and use with sample code

### Expected Behavior

I should be able to run porcupine properly with the files being provided by picovoice and their linked github files, but the model file hosted on github ([https://github.com/Picovoice/porcupine/blob/master/lib/common/porcupine_params.pv](https://github.com/Picovoice/porcupine/blob/master/lib/common/porcupine_params.pv)) seems to be v 2.2.0 according to the error message.

**Comment by mikeglopez** [comment]
Cleared browser cache, got a different issue:

 [0] Model (.pv) file has incorrect format or belongs to a different platform.
  [1] Loading parameters failed with `INVALID_ARGUMENT`.
  [2] Picovoice Error (code `0000012C`)

Reran the base64 conversion command for the model and all errors went away.
