### ISSUE TITLE
PORCUPINE CASUING ERRORS AND NOT RUNNING TRAINED KEYWORD

### ISSUE THREAD

**Issue by MuhammadBilal848** [Picovoice/porcupine#1270]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Porcupine docs
- [X] I have searched the existing issues for Porcupine

### SDK

Python

### Porcupine package version

3.0.2

### Framework version

3.12.3

### Platform

Windows (x86_64)

### OS/Browser version

Chrome - Version 124.0.6367.91 (Official Build) (64-bit)

### Describe the bug

I trained a model using [porcupine console](https://console.picovoice.ai/ppn)  choosing a language and a wake word, then I downloaded the model and got a .ppn file. I put the file in the folder of keywords where all other wake word files are available.

`C:\Users\Bilal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pvporcupine\resources\keyword_files\windows`

![image](https://github.com/Picovoice/porcupine/assets/57318407/548df3ab-080d-472a-973c-c60af0b0dd4f)

When I ran the help using cmd to check if the trained wake word became available, using the command:
```
porcupine_demo_mic -h
```
I got this:
![image](https://github.com/Picovoice/porcupine/assets/57318407/121e19c7-a29c-4ba5-be3f-c6a57e327c2e)

As you can see the wake word file is available "helfen".

When I tried running the file using the command:
```
porcupine_demo_mic --access_key MY_API --keywords helfen
```

I am getting this error:

```
One or more arguments provided to Porcupine is invalid:  Namespace(access_key='My_API', keywords=['helfen'], keyword_paths=None, library_path=None, model_path=None, sensitivities=[0.5], audio_device_index=-1, output_path=None, show_audio_devices=False)
Initialization failed:
  [0] Keyword file (.ppn) file has incorrect format or belongs to a different platform.
  [1] Picovoice Error (code `00000136`)
  [2] Loading keyword file at `C:\Users\Bilal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pvporcupine\resources/keyword_files\windows\helfen_windows.ppn` failed with `INVALID_ARGUME
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Bilal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\Scripts\porcupine_demo_mic.exe\__main__.py", line 7, in <module>
  File "C:\Users\Bilal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pvporcupinedemo\porcupine_demo_mic.py", line 97, in main
    raise e
  File "C:\Users\Bilal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pvporcupinedemo\porcupine_demo_mic.py", line 88, in main
    porcupine = pvporcupine.create(
                ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bilal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pvporcupine\_factory.py", line 69, in create
    return Porcupine(
           ^^^^^^^^^^
  File "C:\Users\Bilal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pvporcupine\_porcupine.py", line 198, in __init__
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status](
pvporcupine._porcupine.PorcupineInvalidArgumentError: Initialization failed:
  [0] Keyword file (.ppn) file has incorrect format or belongs to a different platform.
  [1] Picovoice Error (code `00000136`)
  [2] Loading keyword file at `C:\Users\Bilal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pvporcupine\resources/keyword_files\windows\helfen_windows.ppn` failed with `INVALID_ARGUME
```

How can I resolve this?

### Steps To Reproduce

I do not know.

### Expected Behavior

The code should run the model and be able to detect the word "Helfen"

**Comment by MuhammadBilal848** [comment]
I solved it.

When i trained the model and accidentally i downloaded it in **Android Build** and was running it on Windows.
I again trained the model and downloaded it in **Windows Built** then I ran this command:

```
porcupine_demo_mic --access_key MY_API --keywords helfen
```

Then came another error (🤣):

`  [0] Keyword file (.ppn) and model file (.pv) should belong to the same language. File belongs to `de` while model file (.pv) belongs to `en`.`

This is the language model error, so I downloaded the correct language model from [here](https://github.com/Picovoice/porcupine/tree/master/lib/common) and put it inside "common" folder created by porcupine. and I added model_path arg in the next command and voilaaaa it worked.

The final command was this:

```
porcupine_demo_mic --access_key 7/R+LQ/Uqmpzh3dQFk5s9kA97ktveCl6amEGwZod7Ykh86x/eBXIRg== --keywords helfen --model_path 'C:\Users\Bilal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pvporcupine\lib\common'
```
