### ISSUE TITLE
EnumBadKeyError running python demo 

### ISSUE THREAD

**Issue by irthomasthomas** [Picovoice/Porcupine#138]
Hi, I'm following your youtube tutorial on Ubuntu 18.04 and I receive the following error trying to run the demo...

#python demo/python/porcupine_demo.py --keyword_file_paths ~/projects/Porcupine/ytdemo/'ok computer_linux.ppn' 
listening for:
- ok computer (sensitivity: 0.500000)
 [INFO] Your evaluation license will expire in 89 days
Traceback (most recent call last):
  File "demo/python/porcupine_demo.py", line 222, in <module>
    input_device_index=args.input_audio_device_index).run()
  File "demo/python/porcupine_demo.py", line 100, in run
    sensitivities=self._sensitivities)
  File "demo/python/../../binding/python/porcupine.py", line 114, in __init__
    byref(self._handle))
  File "/usr/local/lib/python2.7/dist-packages/enum.py", line 199, in __init__
    raise EnumBadKeyError(key)
enum.EnumBadKeyError: Enumeration keys must be strings: 0

**Comment by irthomasthomas** [comment]
Sorry I missed the section on prerequisites. https://github.com/Picovoice/Porcupine/tree/master/binding/python
