### ISSUE TITLE
Android java.io.IOException: Initialization of Porcupine failed

### ISSUE THREAD

**Issue by lukaspetersson** [Picovoice/Porcupine#176]
This issue has been brought up before (#48, #59 ) but have not got a propper answer.

I am trying to import the library to an android project. Gradle syncs correctly. However something is not right and I get the same error when running on emulator as when running on real device.

```
        String keywordFilePath = new File(getFilesDir(), "porcupine.ppn").getAbsolutePath();
        String modelFilePath = new File(getFilesDir(), "params.pv").getAbsolutePath();

        try{
            Porcupine porcupine = new Porcupine(modelFilePath, keywordFilePath, 0.5f);
        }catch (PorcupineException e){
        }
```
this throws an exception : 

```
ai.picovoice.porcupinemanager.PorcupineManagerException: ai.picovoice.porcupine.PorcupineException: java.lang.IllegalArgumentException: Initialization of Porcupine failed.
        at ai.picovoice.porcupinemanager.PorcupineManager.<init>(PorcupineManager.java:97)
        at ai.picovoice.porcupine.demo.MainActivity.initPorcupine(MainActivity.java:106)
        at ai.picovoice.porcupine.demo.MainActivity.process(MainActivity.java:74)
        at java.lang.reflect.Method.invoke(Native Method)
        at android.view.View$DeclaredOnClickListener.onClick(View.java:5680)
        at android.view.View.performClick(View.java:6669)
        at android.widget.CompoundButton.performClick(CompoundButton.java:134)
        at android.view.View.performClickInternal(View.java:6638)
        at android.view.View.access$3100(View.java:789)
        at android.view.View$PerformClick.run(View.java:26145)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: ai.picovoice.porcupine.PorcupineException: java.lang.IllegalArgumentException: Initialization of Porcupine failed.
        at ai.picovoice.porcupine.Porcupine.<init>(Porcupine.java:49)
        at ai.picovoice.porcupinemanager.PorcupineManager.<init>(PorcupineManager.java:95)
        at ai.picovoice.porcupine.demo.MainActivity.initPorcupine(MainActivity.java:106) 
        at ai.picovoice.porcupine.demo.MainActivity.process(MainActivity.java:74) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at android.view.View$DeclaredOnClickListener.onClick(View.java:5680) 
        at android.view.View.performClick(View.java:6669) 
        at android.widget.CompoundButton.performClick(CompoundButton.java:134) 
        at android.view.View.performClickInternal(View.java:6638) 
        at android.view.View.access$3100(View.java:789) 
        at android.view.View$PerformClick.run(View.java:26145) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6863) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: java.lang.IllegalArgumentException: Initialization of Porcupine failed.
        at ai.picovoice.porcupine.Porcupine.init(Native Method)
        at ai.picovoice.porcupine.Porcupine.<init>(Porcupine.java:47)
        at ai.picovoice.porcupinemanager.PorcupineManager.<init>(PorcupineManager.java:95) 
        at ai.picovoice.porcupine.demo.MainActivity.initPorcupine(MainActivity.java:106) 
        at ai.picovoice.porcupine.demo.MainActivity.process(MainActivity.java:74) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at android.view.View$DeclaredOnClickListener.onClick(View.java:5680) 
        at android.view.View.performClick(View.java:6669) 
        at android.widget.CompoundButton.performClick(CompoundButton.java:134) 
        at android.view.View.performClickInternal(View.java:6638) 
        at android.view.View.access$3100(View.java:789) 
        at android.view.View$PerformClick.run(View.java:26145) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6863) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
The file paths given to the constructor are correct, I ran the `exists()` method on the files and it returned true.
```
keywordFilePath:
/data/user/0/com.example.wakewordtest/files/porcupine.ppn
modelFilePath:
/data/user/0/com.example.wakewordtest/files/params.pv
```
This is the project structure:
![image](https://user-images.githubusercontent.com/42323981/57972351-6bf9c900-7999-11e9-829f-adba79b56e4d.png)

After some digging I found that this function in  `Porcupine.java` is not working:
```
private native long init(String modelFilePath, String[] keywordFilePaths, float[] sensitivities);
```

**Comment by kenarsa** [comment]
can you look into your logcat and see what is the error? BTW, which version are you using?

**Comment by kenarsa** [comment]
I only see the exception. If the method fails there must be a log error before the exception. Also, Alexa model file on android is not available on the latest version on GitHub.

**Comment by lukaspetersson** [comment]
I know about the alexa thing, in reallity I used porcupine.ppn (I asked a question on stackoverflow aswell and I did not want to confuse them with a strange name, I have now updated the question).

I see, this is the error I get:
```
I/PICOVOICE:  [INFO] model file path: /data/user/0/ai.picovoice.porcupine.demo/files/params.pv
I/PICOVOICE:  [INFO] number of keywords: 1
I/PICOVOICE:  [INFO] keyword file path [0]: /data/user/0/ai.picovoice.porcupine.demo/files/porcupine.ppn
I/PICOVOICE:  [INFO] sensitivity [0]: 0.500000
I/PICOVOICE: [ERROR] keyword file has incorrect format or belongs to a different platform
I/PICOVOICE: [ERROR] loading keyword file #0 failed with 'INVALID_ARGUMENT'
```

**Comment by kenarsa** [comment]
The error file is saying that keyword file belongs to a different platform. you are probably not using porcupine_android.ppn

**Comment by lukaspetersson** [comment]
is porcupine_android.ppn a different file from porcupine.ppn. In the sample project porcupine.ppn is automatically installed on the device, that is the file I am using.

**Comment by kenarsa** [comment]
That's a symlink to porcupine_android ... Since you are on windows your os might not understand symlinks properly. Just grab the android file

**Comment by lukaspetersson** [comment]
I see, now I took the porcupine_android.ppn file instead and uploaded it to the device so that the `exists()` method returns true. But now I get a new error which crashes the app completely:

```
I/PICOVOICE:  [INFO] model file path: /data/user/0/ai.picovoice.porcupine.demo/files/params.pv
I/PICOVOICE:  [INFO] number of keywords: 1
I/PICOVOICE:  [INFO] keyword file path [0]: /data/user/0/ai.picovoice.porcupine.demo/files/porcupine_android.ppn
I/PICOVOICE:  [INFO] sensitivity [0]: 0.500000
I/PICOVOICE: [ERROR] invalid parameter file format.
```

**Comment by kenarsa** [comment]
now its saying .pv format is wrong. is there file there? this file is not platform-dependent. I suggest running the demo app without any modifications and go from there.

**Comment by lukaspetersson** [comment]
I cloned a fresh version of the masterbranch and once again ran the demo.

 however, in order to run and build the app (I am on a windows) I had to copy and paste som files and folders in replacement of the symlinks. I had to do this for the "porcupine" library (binding\android\porcupine) and the libs (\lib\android).

I made no other changes. 

After that I ran the app and when i click start I once again get the error: 

```
I/PICOVOICE:  [INFO] model file path: /data/user/0/ai.picovoice.porcupine.demo/files/params.pv
I/PICOVOICE:  [INFO] number of keywords: 1
I/PICOVOICE:  [INFO] keyword file path [0]: /data/user/0/ai.picovoice.porcupine.demo/files/porcupine_android.ppn
I/PICOVOICE:  [INFO] sensitivity [0]: 0.500000
I/PICOVOICE: [ERROR] invalid parameter file format.
```

**Comment by kenarsa** [comment]
for some reason the file does not get to android correctly. I can't tell you why as I don't develop on windows. to confirm might be good idea to try to read the file inside android and try to verify the content.

**Comment by lukaspetersson** [comment]
params.pv was also a symlink, I pasted the file instead and it worked. Thank you!
