### ISSUE TITLE
C# Integration recording problem

### ISSUE THREAD

**Issue by adriansd27** [Picovoice/Porcupine#179]
Hi,
I'm trying to run the .NET demo, and I'm running into some problems.

I'm getting the following exception:
`System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'`
StackTrace: 

```
   at Arthur.WindowsClient.Services.Porcupine.pv_porcupine_process(IntPtr pointer, Int16[] voiceData, Boolean& results)
   at Arthur.WindowsClient.Services.Porcupine.Process(Int16[] data, Boolean& result) in path\to\file\Services\Porcupine.cs:line 106
   at Arthur.WindowsClient.Services.HotWordDetection.Start() in path\to\file\Services\HotWordDetection.cs:line 52
   at Arthur.WindowsClient.ConsoleAppTest.Program.Main() in path\to\file\ConsoleAppTest\Program.cs:line 50
```

### Steps to reproduce the behavior
I've set the build action to Any CPU

This is my code:

```
public class HotWordDetection
    {
        private short[] GetNextAudioFrame()
        {
            if (WaveIn.DeviceCount < 1)
            {
                Console.WriteLine("No microphone!");
            }

            // some functionality that gets the next frame
            var waveIn = new WaveInEvent
            {
                DeviceNumber = 0,
                WaveFormat = new WaveFormat(16000, 1)
            };
            var writeLock = new object();

            byte[] data = new byte[8192];

            waveIn.DataAvailable += (sender, args) =>
            {
                lock (writeLock)
                {
                    Buffer.BlockCopy(args.Buffer, 0, data, 0, args.BytesRecorded);
                }
            };
            waveIn.StartRecording();
            Console.WriteLine("Listening...");

            //Task.Delay(TimeSpan.FromSeconds(3));
            Thread.Sleep(3000);
            waveIn.StopRecording();
            List<short> frames = new List<short>();

            foreach (var value in data)
            {
                frames.Add(value);
            }
            return frames.ToArray();
        }

        public void Start()
        {
            string modelFilePath = @"path\to\file\porcupine_params.pv";
            float sensitivity = (float)0.5;
            string keyword_file_path = @"path\to\file\alexa_windows.ppn";

            Porcupine instance = new Porcupine(modelFilePath, keyword_file_path, sensitivity);

            int i = 0;

            while (true)
            {
                Console.WriteLine(i++);
                var frame = GetNextAudioFrame();
                var status = instance.Process(frame, out var result);
                if (status != PicoVoiceStatus.SUCCESS)
                {
                    // error handling logic
                }
                if (result)
                {
                    // detection event logic/callback
                    Console.WriteLine("SUCCESS");

                    Thread.Sleep(5000);
                }
            }
        }
    }

```
This happens after 79 iterations of the while loop.
I believe it might be a problem with the recording. I would appreciate it very much if you could help me with this issue.

**Comment by adriansd27** [comment]
OK, so I've modified the GetNextAudioFrame() as seen in the question. Now it's getting recording data fine (I think, the array is populated with values). There are no more exceptions thrown, but it's still not being triggered by the "Alexa" hotword used from the alexa_windows.ppn file. Is there anything I'm doing wrong?

**Comment by kenarsa** [comment]
frame needs to have 512 samples in it.

**Comment by adriansd27** [comment]
this means that the frames array should have 512 values?

**Comment by dpgindler** [comment]
You are getting further than I am..  I can't get pv_porcupine_init to return without an error.  My paths seem fine...   
"D:\\SoftwareDev\\Cloud\\VoiceDemoConsoleApp\\model\\porcupine_params.pv"
"D:\\SoftwareDev\\Cloud\\VoiceDemoConsoleApp\\keywords\\hey_pico.ppn"

ideas?

**Comment by dpgindler** [comment]
You are getting further than I am.. I can't get pv_porcupine_init to return without an error. My paths seem fine...
From debugger window:
"D:\SoftwareDev\Cloud\VoiceDemoConsoleApp\model\porcupine_params.pv"
"D:\\SoftwareDev\\Cloud\\VoiceDemoConsoleApp\\keywords\\alexa_windows..ppn"

ideas?

**Comment by dpgindler** [comment]
Adrian -  Did you get this figured out?

I am trying to do something similar.  Wondering what the issue is here.

**Comment by adriansd27** [comment]
Hi,

I did a workaround. I saved the recorded bytes as a wav file. Then, I loaded the wav file just like they did in the example project. Let me know If this works for you or if you figure out a better method to aquire this.

**Comment by dpgindler** [comment]
Do you mind sharing your code for that?

**Comment by kenarsa** [comment]
closing due to inactivity.

**Comment by koskit** [comment]
Hello everyone!

Soooooo, after a day or two of testing, bruteforcing solutions, reading about inputs, sample rates, naudio waaaaves and whatnot, I've solved this.

There are two "inconveniences" about integrating nAudio with Porcupine.

1. As @kenarsa pointed out on your code @adriansd27 , porcupine expects to process only 512 samples each time, while nAudio, depending on your sample rate, it returns a fixed amount (for the fixed sample rate of 16000 that porcupine needs, nAudio returns 3200 bytes or recorded audio). To get the samples, we have to BlockCopy `Buffer.BlockCopy(e.Buffer, 0, sampleData, 0, e.BytesRecorded);` all of the bytes to short[]. Each short is 2 bytes (16 bits) by definition. So. ok, we get 3200 bytes from nAudio, when divided by 2, we still have 1600 shorts, when we must use only 512 of them. So we come to the next problem.

2. We have to keep these shorts somewhere so we can "spoon-feed" porcupine with the right amount of shorts (512). Also, it needs to be in a "queue" manner. We have to give them in the right order, otherwise the sound they represent isn't correct. For example, even if we give them in short batches (e.g. make some threads and `Process` them with porcupine in asynchronous manner), we might end up with incorrect order, i.e. the "blueberry" word might come out as "berryblue" or even worse, "beblruery",

So, where we go:

First, create a class that wraps a queue, and handles batches of shorts (512 to be exact). This class should do the following:
- We give it some shorts, no matter how many, 100, 500.000, 1.000.000, and it stores them.
- Whenever the amount of shorts reaches 512 or more, we must remove these 512 shorts from the queue, and then send them to anyone who cares to have them.

The class (implemented as Generic, not only for shorts, for any potential future use):
```
public class BufferBatch<T>
{
    private readonly ConcurrentQueue<T> _Queue;
    private readonly object _Lock;
    private readonly int _BatchSize;

    /// <summary>
    /// Event handler that raises events whenever a new batch is ready.
    /// </summary>
    public event EventHandler<BufferBatchReadyEventArgs<T>> OnBatchReady;

    /// <summary>
    /// Writes the given items to the buffer.
    /// </summary>
    /// <param name="items"></param>
    public void Write(IEnumerable<T> items)
    {
        lock (_Lock)
        {
            //Add the items to the queue.
            foreach (T item in items)
            {
                _Queue.Enqueue(item);
            }

            //Begin sending as many batches as we can.
            while (_Queue.Count >= _BatchSize)
            {
                //Dequeue the items.
                List<T> batch = new List<T>();
                for (int i = 0; i < _BatchSize; i++)
                {
                    _Queue.TryDequeue(out T item);
                    batch.Add(item);
                }

                //Send the batch to anyone listening.
                OnBatchReady?.Invoke(
                    this,
                    new BufferBatchReadyEventArgs<T>(batch));
            }
        }
    }

    /// <summary>
    /// Creates a new instance of the class.
    /// </summary>
    /// <param name="batchSize">The size of the batches.</param>
    public BufferBatch(int batchSize)
    {
        _Queue = new ConcurrentQueue<T>();
        _Lock = new object();
        _BatchSize = batchSize;
    }
}

public class BufferBatchReadyEventArgs<T> : EventArgs
{
    public IEnumerable<T> Items { get; private set; }
    public BufferBatchReadyEventArgs(IEnumerable<T> items)
    {
        Items = items;
    }
}
```

Now, we need a class that will handle the recording, and whenever there is new data from our microphone, will store them to the `BufferBatch`. This class will also use nAudio, and will handle the conversion from bytes (that nAudio gives) to the Shorts (the porcupine expects). So it will have a `WaveInEvent` that will handle async recording of the microphone input, and will have the `BufferBatch`. 

Let's name it `class MicrophoneSampleProvider` since it provides small samples `short[512] arrays` from a microphone device.

```
/// <summary>
/// Class that provides samples from an input (microphone) device.
/// </summary>
public class MicrophoneSampleProvider
{
    #region [Private Fields]

    private readonly BufferBatch<short> _BufferBatch;
    private readonly WaveInEvent _SourceStream;

    #endregion [Private Fields]

    #region [Public Properties]

    public string MicrophoneDeviceName { get; private set; }

    #endregion [Public Properties]

    #region [Event Handlers]

    /// <summary>
    /// Event handler that raises events whenever a new samples batch is ready.
    /// </summary>
    public event EventHandler<MicrophoneSamplesEventArgs> OnReadySamples;

    #endregion [Event Handlers]

    #region [Listeners]

    /// <summary>
    /// Adds the new recording data to the batched buffer.
    /// </summary>
    private void OnNewRecordingData(object sender, WaveInEventArgs e)
    {
        //Each sample (short) takes up 2 bytes. So when we copy the buffer
        //over to the short[] array, we need half the capacity. (2 bytes => 1 short).
        int samplesCount = e.BytesRecorded / 2;
        short[] sampleData = new short[samplesCount];

        //Copy/covert the event args buffer to samples.
        Buffer.BlockCopy(e.Buffer, 0, sampleData, 0, e.BytesRecorded);

        //Write the data to the buffer. If the items count reach more than the limit,
        //it will handle itself and raise the appropriate events.
        _BufferBatch.Write(sampleData);
    }

    /// <summary>
    /// Raises a new OnReadySample event whenever a buffer batch is ready.
    /// </summary>
    private void OnBufferBatchReady(object sender, BufferBatchReadyEventArgs<short> e)
    {
        //Whenever a new batch is ready, send the samples to whoever is listening to "OnReadySamples".
        OnReadySamples?.Invoke(
            this,
            new MicrophoneSamplesEventArgs(e.Items.ToArray()));
    }

    #endregion [Listeners]

    #region [Public Methods]

    /// <summary>
    /// Starts recording.
    /// </summary>
    public void StartRecording()
    {
        _SourceStream.StartRecording();
    }

    /// <summary>
    /// Stops recording.
    /// </summary>
    public void StopRecording()
    {
        _SourceStream.StopRecording();
        _SourceStream.Dispose();
    }

    #endregion [Public Methods]

    #region [Constructor]

    /// <summary>
    /// Creates a new instance of the class.
    /// </summary>
    /// <param name="deviceNumber">The device (microphone) to attach nAudio to. Takes the OS default as default parameter (id = 0).</param>
    /// <param name="bufferLimit">The buffer limit, that, when reached, a new OnReadySamples event will be raised. Porcupine default = 512.</param>
    /// <param name="sampleRate">The sample rate of the microphone device. Porcupine default = 16000.</param>
    public MicrophoneSampleProvider(int deviceNumber = 0, int sampleRate = 16000, int bufferLimit = 512)
    {
        WaveInCapabilities deviceCapabilities = 
            WaveInEvent.GetCapabilities(deviceNumber);

        MicrophoneDeviceName = deviceCapabilities.ProductName;

        _SourceStream = new WaveInEvent
        {
            DeviceNumber = deviceNumber,
            WaveFormat = new WaveFormat(sampleRate, 1)
        };
        _SourceStream.DataAvailable += OnNewRecordingData;

        _BufferBatch = new BufferBatch<short>(bufferLimit);
        _BufferBatch.OnBatchReady += OnBufferBatchReady;
    }

    #endregion [Constructor]        
}

public class MicrophoneSamplesEventArgs : EventArgs
{
    public short[] Samples { get; private set; }

    public MicrophoneSamplesEventArgs(short[] samples)
    {
        Samples = samples;
    }
}
```

I hope the documentation is enough to get the gist of it and I didn't mess anything up.

Now, lets make one more class. This class will wrap the porcupine class, in order to make everything pretty for us (and to be easier to use it in the future). Let's make `class WakeWordDetector`. This class will have an EventHandler an event gets raised each time a keyword is used. It will also handle some minor construction code whenever we create a new `Pv.Porcupine` instance etc.

```
/// <summary>
/// Class that contains logic on detecting certain "wake" words from an audio input.
/// </summary>
public class WakeWordDetector
{
    #region [Private Fields]

    private readonly Pv.Porcupine _Porcupine;
    private readonly string[] _Keywords;

    #endregion [Private Fields]

    #region [Public Properties]

    /// <summary>
    /// The keywords the detector listens to.
    /// </summary>
    public IEnumerable<string> Keywords => _Keywords;

    /// <summary>
    /// The microphone sample provider that the class uses to process audio and
    /// detect wake words.
    /// </summary>
    public MicrophoneSampleProvider MicrophoneSampleProvider { get; private set; }

    #endregion [Public Properties]

    #region [Event Handlers]

    /// <summary>
    /// Event handler that fires when a wake word is detected.
    /// </summary>
    public event EventHandler<WakeWordDetectedEventArgs> OnWakeWord;

    #endregion [Event Handlers]

    #region [Listeners]

    /// <summary>
    /// Process the new microphone samples, and if a wake word is detected, raise
    /// an OnWakeWord event.
    /// </summary>
    /// <param name="sender"></param>
    /// <param name="e"></param>
    private void OnNewMicrophoneSamples(object sender, MicrophoneSamplesEventArgs e)
    {
        int result = _Porcupine.Process(e.Samples);

        //Raise an event in case of keyword.
        if (result >= 0)
            OnWakeWord?.Invoke(
                this,
                new WakeWordDetectedEventArgs(
                    _Keywords[result],
                    DateTimeOffset.Now));
    }

    #endregion [Listeners]

    #region [Public Methods]

    /// <summary>
    /// Starts listening for wake words.
    /// </summary>
    public void StartListening()
    {
        MicrophoneSampleProvider.StartRecording();
    }

    /// <summary>
    /// Stops listening for wake words.
    /// </summary>
    public void StopListening()
    {
        MicrophoneSampleProvider.StopRecording();
    }

    #endregion [Public Methods]

    #region [Constructor]

    /// <summary>
    /// Creates a new wake word detector.
    /// </summary>
    /// <param name="modelPath">The model path. If left null, will search at the default location.</param>
    /// <param name="keywords">The keywords to listen for.</param>
    public WakeWordDetector(string modelPath = null, params string[] keywords)
    {
        //Build the model path. If no model path specified, search at default path.
        if (modelPath == null)
        {
            string currentDirectory = Path.GetDirectoryName(Assembly.GetEntryAssembly().Location);
            string commonModelPath = @"lib\\common\\porcupine_params.pv";
            string expectedModelPath = Path.Combine(currentDirectory, commonModelPath);

            if (!File.Exists(expectedModelPath))
                throw new FileNotFoundException(
                    $"[{nameof(WakeWordDetector)}] Tried to find model path at path {expectedModelPath}." +
                    $" No model found. Please set the model path at construction time.");

            modelPath = expectedModelPath;
        }

        //Build the keywords. If no keywords specified, use all default.
        if (keywords.Length == 0)
            keywords = Pv.Porcupine.KEYWORDS.ToArray();

        //Keep a class variable with the keywords so we can find which keyword was proccessed.
        _Keywords = keywords;

        //Create porcupine instance by searching for each keyword location, and add a default frequency for each keyword.
        _Porcupine = new Pv.Porcupine(
            modelPath,
            _Keywords.Select(k => Pv.Porcupine.KEYWORD_PATHS[k]),
            Enumerable.Repeat(0.5f, keywords.Count()));

        //Use constructor defaults.
        MicrophoneSampleProvider = new MicrophoneSampleProvider();
        MicrophoneSampleProvider.OnReadySamples += OnNewMicrophoneSamples;
    }

    #endregion [Constructor]    
}

public class WakeWordDetectedEventArgs : EventArgs
{
    public WakeWordDetectedEventArgs(string keyword, DateTimeOffset timeProccessed)
    {
        Keyword = keyword;
        TimeProccessed = timeProccessed;
    }

    public string Keyword { get; private set; }
    public DateTimeOffset TimeProccessed { get; private set; }
}
```

You should probably modify the classes to fit your needs. Probably most modifications will be on constructor of `WakeWordDetector` to pass keyword files etc. But as is, by default, it should load all keywords that come with the nuget package of porcupine.

You can test the implementation with the code below that listens for keywords for 60 seconds:

```
class Program
{
    static void Main(string[] args)
    {
        WakeWordDetector wakeWordDetector = new WakeWordDetector();
        wakeWordDetector.OnWakeWord += LogToConsole;

        Console.WriteLine("Keywords to listen for: ");
        wakeWordDetector.Keywords.ToList().ForEach(k => Console.WriteLine(k));

        Console.WriteLine($"Started listening with device {wakeWordDetector.MicrophoneSampleProvider.MicrophoneDeviceName}...");
        wakeWordDetector.StartListening();

        Thread.Sleep(60 * 1000);

        Console.WriteLine("Stopped listening...");
        wakeWordDetector.StopListening();

        Console.WriteLine("Press <Return> to exit.");
        Console.ReadLine();
    }

    private static void LogToConsole(object sender, WakeWordDetectedEventArgs e)
    {
        Console.WriteLine($"[{e.TimeProccessed:o}] {e.Keyword}");
    }
}
```

Well, that's all. @kenarsa with your permission, I could code it in a more simple manner with the bare minimum and create a pull request for the nuget package (to make it easier), or even create a `Porcupine.Integrations.NAudio` package. Otherwise, let's just leave it here for anyone that might come across the same problem in the future.

**Comment by kenarsa** [comment]
hey @koskit! thanks for this. Did you check out our new C# SDK? :) We moved to OpenAL for C# demos.

**Comment by koskit** [comment]
hey @kenarsa , no, I couldn't find any reference, could you share the link? I probably searched in the wrong section :)

**Comment by koskit** [comment]
@kenarsa Oh, I'm dumb, yes, I've downloaded the OpenAL and checked the demo. It played a major role in writing the code above. 😄 

Unfortunately, as I'm trying to create self contained .net core apps for deployment on rpi both on Windows IOT Core and Raspbian, I have set myself a rule about only using nuget packages with no dependencies on other programs. From what I saw on OpenAL download section, both the windows installer and the core package are install-ables that need to be installed on that machine before running any application dependent on them. On the other hand, with nuget packages, (and on our case, nAudio)  I just have to include the assemblies on the .net core project and the dependencies get deployed along with the app.

Anyways, thanks for you input. I appreciate it. Keep up the awesome work.
I have to say, as my first experience with wake-word implementations and speech-to-text in general, when I saw porcupine, it was something else. Really impressed!

**Comment by laves** [comment]
Hi @koskit, 

Thanks for your interest in Porcupine - seems like you did a lot of good work here! I'm the developer who implemented the .NET SDK and worked on the demos. We were very interested in getting .NET Core running on Raspbian at the time of implementation, but had to move on to other SDKs before we could get a dependable version running.

The main issue with running on the rpi was to do with loading the correct Porcupine library file for the specific ARM architecture of rpi the developer is using. We use DllImport to load the Porcupine library in our SDK and it has a limitation with respect to detecting the proper architecture. When running on a Linux system it will just grab the first libpv_porcupine.so it finds and not select based on architecture. We could solve this with the [NativeLibrary](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.nativelibrary?view=net-5.0) class and some additional platform detection logic, but it would restrict our support to .NET Core 3.0+ and we were trying to keep .NET Framework devs happy. We will eventually move in this direction if there's enough interest since .NET Framework is coming up on end-of-support in the next few years.

The other issue you may encounter has to do with NAudio. We initially used NAudio in our demos, but found that it doesn't support cross-platform audio input. Unfortunately, as it stands, NAudio's audio recording capabilities are restricted to Windows, though they do support file reading and the like on other OSs. The reason we moved to OpenAL is because of it's audio input support on Windows, macOS and Linux. If you want your application to run on Raspbian, you would not be able to use NAudio, so you may want to consider either restricting to Windows IoT Core or finding a way of integrating OpenAL into your application. It may work if you just include the OpenAL .dll and .so with your application.

All that said, these are not issues that should prevent you from making Porcupine work for you! I just wanted to make you aware of .NET Core limitations we encountered while implementing the SDK and demos. If you can overcome any of these limitations we'd love to hear about it and open a feature request for it as IoT Core and Raspbian are definitely OSs we'd love to support with our .NET SDK. 

ps - if you use static `create` constructor you can make Porcupine with simply `Porcupine.Create(keywords:Porcupine.KEYWORDS)` and it will fill in the modelPath, sensitivities and keywordPaths for you!

**Comment by koskit** [comment]
Hey @laves !

I see. I should have done my research better. I will try your approach (using OpenAL.dll) and report any findings/resolutions on the problems you encountered. 

Thank you so much for your input and your time.

Cheers!
