### ISSUE TITLE
Android - can't build demo app

### ISSUE THREAD

**Issue by rcleaves** [Picovoice/Porcupine#199]
### Expected behavior

The codebase from github should build and run as-is. 

### Actual behavior

The app doesn't build or run in Android Studio.

in Android Studio, the build console shows the errors:

Unable to resolve dependency for ':porcupinemanager@debug/compileClasspath': Could not resolve project :porcupine. Show Details Affected Modules: porcupinemanager |  
-- | --
Unable to resolve dependency for ':porcupinemanager@debugAndroidTest/compileClasspath': Could not resolve project :porcupine. Show Details Affected Modules: porcupinemanager |  
Unable to resolve dependency for ':porcupinemanager@debugUnitTest/compileClasspath': Could not resolve project :porcupine. Show Details Affected Modules: porcupinemanager |  

### Steps to reproduce the behavior

1. clone the repo from github: 

$ git clone https://github.com/Picovoice/Porcupine.git

2. open the demo app in Android Studio

File->Open (select the demo app from the cloned repo)

**Comment by kenarsa** [comment]
I tried to reproduce but it actually builds on my machine with no errors. What is the OS and version of Android Studio you are using? Are there any local changes ?

**Comment by rcleaves** [comment]
WIndows 10, AS 3.4.2 and JRE 1.8. no local changes, code cloned from github.

**Comment by rcleaves** [comment]
got past the build issue, but now getting the runtime error:

 Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/ai.picovoice.porcupine.demo-3IWWgdWVhXTqeN9WWNC_hA==/base.apk", zip file "/data/app/ai.picovoice.porcupine.demo-3IWWgdWVhXTqeN9WWNC_hA==/split_lib_dependencies_apk.apk", zip file "/data/app/ai.picovoice.porcupine.demo-3IWWgdWVhXTqeN9WWNC_hA==/split_lib_resources_apk.apk", zip file "/data/app/ai.picovoice.porcupine.demo-3IWWgdWVhXTqeN9WWNC_hA==/split_lib_slice_0_apk.apk", zip file "/data/app/ai.picovoice.porcupine.demo-3IWWgdWVhXTqeN9WWNC_hA==/split_lib_slice_1_apk.apk", zip file "/data/app/ai.picovoice.porcupine.demo-3IWWgdWVhXTqeN9WWNC_hA==/split_lib_slice_2_apk.apk", zip file "/data/app/ai.picovoice.porcupine.demo-3IWWgdWVhXTqeN9WWNC_hA==/split_lib_slice_3_apk.apk", zip file "/data/app/ai.picovoice.porcupine.demo-3IWWgdWVhXTqeN9WWNC_hA==/split_lib_slice_4_apk.apk", zip file "/data/app/ai.picovoice.porcupine.demo-3IWWgdWVhXTqeN9WWNC_hA==/split_lib_slice_5_apk.apk", zip file "/data/app/ai.picovoice.porcupine.demo-3IWWgdWVhXTqeN9WWNC_hA==/split_lib_slice_6_apk.apk", zip file "/data/app/ai.picovoice.porcupine.demo-3IWWgdWVhXTqeN9WWNC_hA==/split_lib_slice_7_apk.apk", zip file "/data/app/ai.picovoice.porcupine.demo-3IWWgdWVhXTqeN9WWNC_hA==/split_lib_slice_8_apk.apk", zip file "/data/app/ai.picovoice.porcupine.demo-3IWWgdWVhXTqeN9WWNC_hA==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/ai.picovoice.porcupine.demo-3IWWgdWVhXTqeN9WWNC_hA==/lib/arm64, /system/lib64, /vendor/lib64, /system/product/lib64]]] **couldn't find "libpv_porcupine.so"**
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)

**Comment by kenarsa** [comment]
If you can build on Ubuntu or Mac, I suggest going down that path. You still can build on Windows but you need to copy-paste all the assets that are symlinks in the repository. I'm going to add this to the documentation of repo and then comment here.

**Comment by kenarsa** [comment]
https://github.com/Picovoice/Porcupine/tree/master/binding/android#note-for-building-on-windows

https://github.com/Picovoice/Porcupine/tree/master/demo/android#note-for-building-on-windows

**Comment by rcleaves** [comment]
Ok, I re-cloned the repo and followed the instructions to build and test the binding and demo. Everything builds but there is a runtime exception during init():

IllegalArguments exception: Initialization of Porcupine failed.

I confirmed that all the raw resource files exist and are not symlinks under the demo directory structure.

**Comment by kenarsa** [comment]
Make sure you do that for the binding project as well. If stilll doesn't work please attach the relevant part of error logs ..

**Comment by rcleaves** [comment]
Yep, did that for binding as well. Unfortunately, the demo code catches the exceptions and doesn't log them, it just throws a toast saying "Something went wrong". I did look at the device file system and see those resources. I have attached a screenshot of the exception caught in the debugger. 
![porc_err](https://user-images.githubusercontent.com/887282/62492893-6d05ef80-b76b-11e9-993c-5f39214b5ae7.PNG)

**Comment by rcleaves** [comment]
added log for error mentioned above:

2019-08-05 10:37:36.099 17145-17145/ai.picovoice.porcupine.demo E/ai.picovoice.porcupine.Porcupine: caught: java.lang.IllegalArgumentException: Initialization of Porcupine failed.
    java.lang.IllegalArgumentException: Initialization of Porcupine failed.
        at ai.picovoice.porcupine.Porcupine.init(Native Method)
        at ai.picovoice.porcupine.Porcupine.<init>(Porcupine.java:49)
        at ai.picovoice.porcupinemanager.PorcupineManager.<init>(PorcupineManager.java:95)
        at ai.picovoice.porcupine.demo.MainActivity.initPorcupine(MainActivity.java:104)
        at ai.picovoice.porcupine.demo.MainActivity.process(MainActivity.java:75)
        at java.lang.reflect.Method.invoke(Native Method)
        at android.view.View$DeclaredOnClickListener.onClick(View.java:5647)
        at android.view.View.performClick(View.java:6615)
        at android.widget.CompoundButton.performClick(CompoundButton.java:134)
        at android.view.View.performClickInternal(View.java:6592)
        at android.view.View.access$3100(View.java:782)
        at android.view.View$PerformClick.run(View.java:25907)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6831)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by kenarsa** [comment]
There should more logs from JNI. That can shed some light here.

**Comment by rcleaves** [comment]
Do the native lib files support debug mode (libv_porcupine.so)? I don't see anything in logcat.

**Comment by kenarsa** [comment]
the current version would log as well. unless the shared object is not loaded on the phone ...
again, if all the symlinks are copied correctly this should work.

**Comment by rcleaves** [comment]
Looks like this is the problem:

2019-08-06 08:40:17.021 9998-9998/ai.picovoice.porcupine.demo I/PICOVOICE: [ERROR] loading keyword file #0 failed with 'INVALID_ARGUMENT'

Here are the complete logs. 


2019-08-06 08:40:03.314 9998-9998/ai.picovoice.porcupine.demo I/System.out: waiting for debugger to settle...
2019-08-06 08:40:03.516 9998-9998/ai.picovoice.porcupine.demo I/System.out: debugger has settled (1437)
2019-08-06 08:40:04.127 9998-9998/ai.picovoice.porcupine.demo I/.porcupine.dem: The ClassLoaderContext is a special shared library.
2019-08-06 08:40:04.851 9998-9998/ai.picovoice.porcupine.demo W/.porcupine.dem: JIT profile information will not be recorded: profile file does not exits.
2019-08-06 08:40:04.872 9998-9998/ai.picovoice.porcupine.demo I/chatty: uid=10159(ai.picovoice.porcupine.demo) identical 10 lines
2019-08-06 08:40:04.873 9998-9998/ai.picovoice.porcupine.demo W/.porcupine.dem: JIT profile information will not be recorded: profile file does not exits.
2019-08-06 08:40:05.953 9998-9998/ai.picovoice.porcupine.demo I/Perf: Connecting to perf service.
2019-08-06 08:40:05.994 9998-9998/ai.picovoice.porcupine.demo V/ActivityThread: installContentProviders Call ai.picovoice.porcupine.demo
2019-08-06 08:40:06.000 9998-9998/ai.picovoice.porcupine.demo I/InstantRun: starting instant run server: is main process
2019-08-06 08:40:06.006 9998-9998/ai.picovoice.porcupine.demo V/ActivityThread: publishContentProviders Call
2019-08-06 08:40:06.539 9998-9998/ai.picovoice.porcupine.demo W/.porcupine.dem: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (light greylist, reflection)
2019-08-06 08:40:06.542 9998-9998/ai.picovoice.porcupine.demo W/.porcupine.dem: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (light greylist, reflection)
2019-08-06 08:40:06.948 9998-9998/ai.picovoice.porcupine.demo D/OpenGLRenderer: Skia GL Pipeline
2019-08-06 08:40:07.194 9998-10088/ai.picovoice.porcupine.demo I/Adreno: QUALCOMM build                   : e258aea, Ib44fd07b22
    Build Date                       : 12/25/18
    OpenGL ES Shader Compiler Version: EV031.25.03.02
    Local Branch                     : 
    Remote Branch                    : 
    Remote Branch                    : 
    Reconstruct Branch               : 
2019-08-06 08:40:07.194 9998-10088/ai.picovoice.porcupine.demo I/Adreno: Build Config                     : S L 6.0.7 AArch64
2019-08-06 08:40:08.783 9998-10088/ai.picovoice.porcupine.demo I/Adreno: PFP: 0x005ff112, ME: 0x005ff066
2019-08-06 08:40:08.788 9998-10088/ai.picovoice.porcupine.demo I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
2019-08-06 08:40:08.788 9998-10088/ai.picovoice.porcupine.demo I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2019-08-06 08:40:08.789 9998-10088/ai.picovoice.porcupine.demo I/OpenGLRenderer: Initialized EGL, version 1.4
2019-08-06 08:40:08.789 9998-10088/ai.picovoice.porcupine.demo D/OpenGLRenderer: Swap behavior 2
2019-08-06 08:40:08.914 9998-9998/ai.picovoice.porcupine.demo I/Choreographer: Skipped 112 frames!  The application may be doing too much work on its main thread.
2019-08-06 08:40:09.010 9998-10088/ai.picovoice.porcupine.demo I/OpenGLRenderer: Davey! duration=1967ms; Flags=0, IntendedVsync=584612153235, Vsync=586478819827, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=586484225763, AnimationStart=586484462377, PerformTraversalsStart=586486592065, DrawStart=586507896336, SyncQueued=586545508888, SyncStart=586545655867, IssueDrawCommandsStart=586545836127, SwapBuffers=586576829982, FrameCompleted=586579412846, DequeueBufferDuration=1720000, QueueBufferDuration=431000, 
2019-08-06 08:40:17.020 9998-9998/ai.picovoice.porcupine.demo I/PICOVOICE:  [INFO] model file path: /data/user/0/ai.picovoice.porcupine.demo/files/params.pv
2019-08-06 08:40:17.021 9998-9998/ai.picovoice.porcupine.demo I/PICOVOICE:  [INFO] number of keywords: 1
2019-08-06 08:40:17.021 9998-9998/ai.picovoice.porcupine.demo I/PICOVOICE:  [INFO] keyword file path [0]: /data/user/0/ai.picovoice.porcupine.demo/files/hey_pico.ppn
2019-08-06 08:40:17.021 9998-9998/ai.picovoice.porcupine.demo I/PICOVOICE:  [INFO] sensitivity [0]: 0.500000
2019-08-06 08:40:17.021 9998-9998/ai.picovoice.porcupine.demo I/PICOVOICE: [ERROR] keyword file has incorrect format or belongs to a different platform
2019-08-06 08:40:17.021 9998-9998/ai.picovoice.porcupine.demo I/PICOVOICE: [ERROR] loading keyword file #0 failed with 'INVALID_ARGUMENT'
2019-08-06 08:40:17.034 9998-9998/ai.picovoice.porcupine.demo E/ai.picovoice.porcupine.Porcupine: caught: java.lang.IllegalArgumentException: Initialization of Porcupine failed.
    java.lang.IllegalArgumentException: Initialization of Porcupine failed.
        at ai.picovoice.porcupine.Porcupine.init(Native Method)
        at ai.picovoice.porcupine.Porcupine.<init>(Porcupine.java:49)
        at ai.picovoice.porcupinemanager.PorcupineManager.<init>(PorcupineManager.java:95)
        at ai.picovoice.porcupine.demo.MainActivity.initPorcupine(MainActivity.java:104)
        at ai.picovoice.porcupine.demo.MainActivity.process(MainActivity.java:75)
        at java.lang.reflect.Method.invoke(Native Method)
        at android.view.View$DeclaredOnClickListener.onClick(View.java:5647)
        at android.view.View.performClick(View.java:6615)
        at android.widget.CompoundButton.performClick(CompoundButton.java:134)
        at android.view.View.performClickInternal(View.java:6592)
        at android.view.View.access$3100(View.java:782)
        at android.view.View$PerformClick.run(View.java:25907)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6831)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-08-06 08:40:17.045 9998-10010/ai.picovoice.porcupine.demo I/.porcupine.dem: Background concurrent copying GC freed 2803(884KB) AllocSpace objects, 5(100KB) LOS objects, 49% free, 1748KB/3MB, paused 144us total 566.694ms
2019-08-06 08:40:17.081 9998-9998/ai.picovoice.porcupine.demo I/Choreographer: Skipped 38 frames!  The application may be doing too much work on its main thread.

**Comment by rcleaves** [comment]
or this:

2019-08-06 08:44:05.917 10256-10256/ai.picovoice.porcupine.demo I/PICOVOICE: [ERROR] keyword file has incorrect format or belongs to a different platform

**Comment by kenarsa** [comment]
there you go. how did you copy the keyword files? or I guess which keyword files you copied?

**Comment by rcleaves** [comment]
All the keyword files were pulled over in the cloning of the repo under the raw directory.

**Comment by kenarsa** [comment]
do you manually copy-paste the ppn files? If yes, from which directory here: https://github.com/Picovoice/Porcupine/tree/master/resources/keyword_files

**Comment by rcleaves** [comment]
I did not have to manually copy-paste. they were cloned from here: https://github.com/Picovoice/Porcupine/tree/master/demo/android/app/src/main/res/raw

Are these not valid/correct?

**Comment by kenarsa** [comment]
have you read through this?

https://github.com/Picovoice/Porcupine/blob/master/binding/android/README.md#note-for-building-on-windows

they are symlinks. windows does not understand symlinks. you need to copy and rename them manually. for example:

resources/keyword_files/android/picovoice_android.ppn -> demo/android/app/src/main/res/raw/picovoice.ppn

**Comment by rcleaves** [comment]
ok making progress, renamed the americano_android.ppn and am now getting the error:

2019-08-06 10:46:50.126 16926-16926/ai.picovoice.porcupine.demo I/PICOVOICE: [ERROR] invalid parameter file format.
2019-08-06 10:46:50.126 16926-16926/ai.picovoice.porcupine.demo A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x736e6574600c40 in tid 16926 (.porcupine.demo), pid 16926 (.porcupine.demo)

Maybe the keyword files are corrupt?

**Comment by kenarsa** [comment]
Please make sure to read the documentation for android deme/binding carefully and pay attention to notes for building on windows. If you follow that all should work.

**Comment by vicianm** [comment]
I'm encountering a very similar error posted by @rcleaves .


Logcat log output:
```
2019-12-14 00:17:41.143 27530-27530/ai.picovoice.porcupine.demo I/PICOVOICE:  [INFO] model file path: /data/user/0/ai.picovoice.porcupine.demo/files/params.pv
2019-12-14 00:17:41.143 27530-27530/ai.picovoice.porcupine.demo I/PICOVOICE:  [INFO] number of keywords: 1
2019-12-14 00:17:41.143 27530-27530/ai.picovoice.porcupine.demo I/PICOVOICE:  [INFO] keyword file path [0]: /data/user/0/ai.picovoice.porcupine.demo/files/hey_pico.ppn
2019-12-14 00:17:41.143 27530-27530/ai.picovoice.porcupine.demo I/PICOVOICE:  [INFO] sensitivity [0]: 0.500000
2019-12-14 00:17:41.144 27530-27530/ai.picovoice.porcupine.demo A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x74726174735f6f in tid 27530 (.porcupine.demo), pid 27530 (.porcupine.demo)
```

I just imported the Android demo from GitHub master repo and fixed the invalid SDK paths in "local.properties" ("/home/alireza/Android/Sdk"). After this fix the app launched on 2 Android devices (one virtual and another a real device) and both failed at runtime.

I tried to consult binding notes as @kenarsa suggests in the comments above, but none of the links work. Or to be more specific the links work but I'm unable to find any "binding notes" at that locations.
- https://github.com/Picovoice/Porcupine/tree/master/binding/android#note-for-building-on-windows
- https://github.com/Picovoice/Porcupine/tree/master/demo/android#note-for-building-on-windows

I even tried to follow another link from Rhino documentation but with the same result: https://github.com/Picovoice/rhino/tree/master/demo/android/RhinoDemo
