### ISSUE TITLE
Unable to run on Huawei P9 phone

### ISSUE THREAD

**Issue by jianrui** [Picovoice/Porcupine#200]
### Expected behavior
Click to “start” speech recognition command words
### Actual behavior
Click to "start" toast prompt error "Something went wrong"，
Click to "stop" app crash

Please include enough details so that the issue can reproduced independently by the resolver.
2019-08-02 12:18:06.894 21053-21053/? I/art: Late-enabling -Xcheck:jni
2019-08-02 12:18:06.894 21053-21053/? I/art: Reinit property: dalvik.vm.checkjni= false
2019-08-02 12:18:07.001 21053-21053/ai.picovoice.porcupine.demo I/InstantRun: starting instant run server: is main process
2019-08-02 12:18:07.017 21053-21053/ai.picovoice.porcupine.demo I/HwCust: Constructor found for class android.app.HwCustActivityImpl
2019-08-02 12:18:07.030 21053-21053/ai.picovoice.porcupine.demo I/HwCust: Constructor found for class android.app.HwCustHwWallpaperManagerImpl
2019-08-02 12:18:07.042 21053-21053/ai.picovoice.porcupine.demo W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
2019-08-02 12:18:07.240 21053-21053/ai.picovoice.porcupine.demo I/BD.Reporter: com.huawei.bd.IBDService$Stub$Proxy@c95b3fa
2019-08-02 12:18:07.256 21053-21053/ai.picovoice.porcupine.demo I/MediaPlayer: setDataSource(49, 384608, 29257)
2019-08-02 12:18:07.276 21053-21053/ai.picovoice.porcupine.demo W/VRSystemServiceManager: vr service is not alive
2019-08-02 12:18:07.280 21053-21053/ai.picovoice.porcupine.demo I/HwPointEventFilter: support AFT
2019-08-02 12:18:07.329 21053-21078/ai.picovoice.porcupine.demo I/OpenGLRenderer: Initialized EGL, version 1.4
2019-08-02 12:18:07.334 21053-21078/ai.picovoice.porcupine.demo W/linker: /vendor/lib64/libhwuibp.so: unused DT entry: type 0xf arg 0xe3a
2019-08-02 12:18:07.341 21053-21053/ai.picovoice.porcupine.demo W/art: Before Android 4.1, method int android.support.v7.widget.DropDownListView.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
2019-08-02 12:18:07.356 21053-21078/ai.picovoice.porcupine.demo E/OpenGLRenderer: allen debug liyu Key: 0
2019-08-02 12:18:07.359 21053-21078/ai.picovoice.porcupine.demo E/OpenGLRenderer: allen debug liyu Key: 34359738371
2019-08-02 12:18:07.360 21053-21078/ai.picovoice.porcupine.demo E/OpenGLRenderer: allen debug liyu Key: 34359738369
2019-08-02 12:18:07.360 21053-21078/ai.picovoice.porcupine.demo E/OpenGLRenderer: allen debug liyu Key: 1
2019-08-02 12:18:07.361 21053-21078/ai.picovoice.porcupine.demo E/OpenGLRenderer: allen debug liyu Key: 240518168576
2019-08-02 12:18:07.361 21053-21078/ai.picovoice.porcupine.demo E/OpenGLRenderer: allen debug liyu Key: 68719476736
2019-08-02 12:18:15.236 21053-21053/ai.picovoice.porcupine.demo I/hwaps: JNI_OnLoad
2019-08-02 12:18:15.362 21053-21053/ai.picovoice.porcupine.demo I/PICOVOICE:  [INFO] model file path: /data/user/0/ai.picovoice.porcupine.demo/files/params.pv
2019-08-02 12:18:15.362 21053-21053/ai.picovoice.porcupine.demo I/PICOVOICE:  [INFO] number of keywords: 1
2019-08-02 12:18:15.362 21053-21053/ai.picovoice.porcupine.demo I/PICOVOICE:  [INFO] keyword file path [0]: /data/user/0/ai.picovoice.porcupine.demo/files/hey_pico.ppn
2019-08-02 12:18:15.362 21053-21053/ai.picovoice.porcupine.demo I/PICOVOICE:  [INFO] sensitivity [0]: 0.500000
2019-08-02 12:18:15.363 21053-21053/ai.picovoice.porcupine.demo I/PICOVOICE: [ERROR] keyword file has incorrect format.
2019-08-02 12:18:15.363 21053-21053/ai.picovoice.porcupine.demo I/PICOVOICE: [ERROR] loading keyword file #0 failed with 'INVALID_ARGUMENT'
2019-08-02 12:18:15.391 21053-21053/ai.picovoice.porcupine.demo W/VRSystemServiceManager: vr service is not alive
2019-08-02 12:18:15.391 21053-21053/ai.picovoice.porcupine.demo W/VRSystemServiceManager: vr service is not alive
2019-08-02 12:18:15.395 21053-21053/ai.picovoice.porcupine.demo I/HwPointEventFilter: support AFT
2019-08-02 12:18:19.658 21053-21053/ai.picovoice.porcupine.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ai.picovoice.porcupine.demo, PID: 21053
    java.lang.IllegalStateException: Could not execute method for android:onClick
        at android.view.View$DeclaredOnClickListener.onClick(View.java:4731)
        at android.view.View.performClick(View.java:5646)
        at android.widget.CompoundButton.performClick(CompoundButton.java:123)
        at android.view.View$PerformClick.run(View.java:22459)
        at android.os.Handler.handleCallback(Handler.java:761)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at android.view.View$DeclaredOnClickListener.onClick(View.java:4726)
        at android.view.View.performClick(View.java:5646) 
        at android.widget.CompoundButton.performClick(CompoundButton.java:123) 
        at android.view.View$PerformClick.run(View.java:22459) 
        at android.os.Handler.handleCallback(Handler.java:761) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:156) 
        at android.app.ActivityThread.main(ActivityThread.java:6523) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) 
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void ai.picovoice.porcupinemanager.PorcupineManager.stop()' on a null object reference
        at ai.picovoice.porcupine.demo.MainActivity.process(MainActivity.java:82)
        at java.lang.reflect.Method.invoke(Native Method) 
        at android.view.View$DeclaredOnClickListener.onClick(View.java:4726) 
        at android.view.View.performClick(View.java:5646) 
        at android.widget.CompoundButton.performClick(CompoundButton.java:123) 
        at android.view.View$PerformClick.run(View.java:22459) 
        at android.os.Handler.handleCallback(Handler.java:761) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:156) 
        at android.app.ActivityThread.main(ActivityThread.java:6523) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) 
2019-08-02 12:18:19.677 21053-21053/ai.picovoice.porcupine.demo I/Process: Sending signal. PID: 21053 SIG: 9

**Comment by kenarsa** [comment]
Did you download the app from store or built it from repository? If you built it from repository what is your OS?

**Comment by kenarsa** [comment]
close due to inactivity.

**Comment by Skuldur** [comment]
I ran into the same issue. I built the app from the repository and ran it using Android Studio.

OS: Windows 10
