### ISSUE TITLE
Crash on click android demo

### ISSUE THREAD

**Issue by esunea** [Picovoice/Porcupine#206]
### Expected behavior
Demo actually works

### Actual behavior

Demo crash when pressing Start Button

### Steps to reproduce the behavior

Build from windows10 - Android studio 3.4
tested on android 9

This may be caused by symlinks on windows not copying correctly. Can you describe steps to fix that ? 

thanks a lot

Please include enough details so that the issue can reproduced independently by the resolver.

2019-08-14 17:43:16.127 22286-22286/ai.picovoice.porcupine.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ai.picovoice.porcupine.demo, PID: 22286
    java.lang.IllegalStateException: Could not execute method for android:onClick
        at android.view.View$DeclaredOnClickListener.onClick(View.java:6073)
        at android.view.View.performClick(View.java:7341)
        at android.widget.TextView.performClick(TextView.java:14162)
        at android.widget.CompoundButton.performClick(CompoundButton.java:143)
        at android.view.View.performClickInternal(View.java:7307)
        at android.view.View.access$3200(View.java:846)
        at android.view.View$PerformClick.run(View.java:27796)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7156)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

**Comment by kenarsa** [comment]
definitely caused by symlinks. you need to find and replace all of them. alternatively build on ubuntu/mac
