### ISSUE TITLE
Can't install dh_segment  

### ISSUE THREAD

**Issue by longwall** [Picovoice/porcupine#210]
I created env  dh_segment followig https://dhsegment.readthedocs.io/en/latest/start/install.html
but when I start
 pip install git+https://github.com/dhlab-epfl/dhSegment
got:

...
Collecting shapely>=1.6.4 (from dh-segment==0.5.0)
  Using cached https://files.pythonhosted.org/packages/a2/fb/7a7af9ef7a35d16fa23b127abee272cfc483ca89029b73e92e93cdf36e6b/Shapely-1.6.4.post2.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'D:\ProgramData\Anaconda3\envs\dh_segment\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\a\\AppData\\Local\\Temp\\pip-install-jiryf6mp\\shapely\\setup.py'"'"'; __file__='"'"'C:\\Users\\a\\AppData\\Local\\Temp\\pip-install-jiryf6mp\\shapely\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\a\AppData\Local\Temp\pip-install-jiryf6mp\shapely\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\a\AppData\Local\Temp\pip-install-jiryf6mp\shapely\setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "C:\Users\a\AppData\Local\Temp\pip-install-jiryf6mp\shapely\shapely\_buildcfg.py", line 200, in <module>
        lgeos = CDLL("geos_c.dll")
      File "D:\ProgramData\Anaconda3\envs\dh_segment\lib\ctypes\__init__.py", line 348, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 126] The specified module could not be found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

The environment is reported to be 64bit:
(dh_segment) 
conda info

     active environment : dh_segment
    active env location : D:\ProgramData\Anaconda3\envs\dh_segment
            shell level : 1
       user config file : C:\Users\a\.condarc
 populated config files : C:\Users\a\.condarc
          conda version : 4.5.11
    conda-build version : 3.15.1
         python version : 3.7.0.final.0
       base environment : D:\ProgramData\Anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/willyd/win-64
                          https://conda.anaconda.org/willyd/noarch
   ...
   ...
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\ProgramData\Anaconda3\pkgs
                          C:\Users\a\AppData\Local\conda\conda\pkgs
       envs directories : D:\ProgramData\Anaconda3\envs
                          C:\Users\a\AppData\Local\conda\conda\envs
                          C:\Users\a\.conda\envs
               platform : win-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Windows/10 Windows/10.0.17134
...

But I'm a little confused with the end "on 32bit" in python.exe output:
python
Python 3.6.7 (default, Jul  2 2019, 02:21:41) [MSC v.1900 64 bit (AMD64)] **on win32**

I will be appreciated for any advice..

**Comment by longwall** [comment]
this solves the problem:
conda install -c conda-forge shapely
