### ISSUE TITLE
Installation on Raspbian fails

### ISSUE THREAD

**Issue by mkarliner** [Picovoice/porcupine#226]
### Steps to reproduce the behaviour
Collecting pvporcupine
Collecting pyaudio (from pvporcupine)
Collecting enum34==1.1.6 (from pvporcupine)
  Using cached https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Collecting pysoundfile>=0.9.0 (from pvporcupine)
  Using cached https://files.pythonhosted.org/packages/2a/b3/0b871e5fd31b9a8e54b4ee359384e705a1ca1e2870706d2f081dc7cc1693/PySoundFile-0.9.0.post1-py2.py3-none-any.whl
Collecting numpy (from pvporcupine)
Collecting cffi>=0.6 (from pysoundfile>=0.9.0->pvporcupine)
Collecting pycparser (from cffi>=0.6->pysoundfile>=0.9.0->pvporcupine)
  Using cached https://www.piwheels.org/simple/pycparser/pycparser-2.19-py2.py3-none-any.whl
Installing collected packages: pyaudio, enum34, pycparser, cffi, pysoundfile, numpy, pvporcupine
Successfully installed cffi-1.13.1 enum34-1.1.6 numpy-1.16.5 pvporcupine-1.6.2 pyaudio-0.2.11 pycparser-2.19 pysoundfile-0.9.0.post1
Segmentation fault

Include enough details so that the issue can be reproduced independently.

lsb_release  -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.11 (stretch)
Release:	9.11
Codename:	stretch

Hardware RPi 3

**Comment by kenarsa** [comment]
based on the message it seems like it actually installed the package. can you confirm?

**Comment by mkarliner** [comment]
Well, yes and no. I hadn't realised that pip's default install dir
for binaries is ./local/bin, and there pvporcupine was however...

 **~/.local/bin/pvporcupine_mic --keywords picovoice**


Traceback (most recent call last):
  File "/home/pi/.local/bin/pvporcupine_mic", line 7, in <module>
    from pvporcupine.demo.python.porcupine_demo import main
  File "/home/pi/.local/lib/python2.7/site-packages/pvporcupine/__init__.py", line 1, in <module>
    from .binding.python.porcupine import Porcupine
ImportError: No module named binding.python.porcupine

**Comment by kenarsa** [comment]
seems like a partial install. I suggest removing and installing again with sudo. I can't reproduce this on an RPI3.

**Comment by mkarliner** [comment]
Removing and installing with sudo worked without error, however
` pvporcupine_mic --keywords picovoice`

resulted in 

Traceback (most recent call last):
  File "/usr/local/bin/pvporcupine_mic", line 7, in <module>
    from pvporcupine.demo.python.porcupine_demo import main
  File "/usr/local/lib/python2.7/dist-packages/pvporcupine/__init__.py", line 1, in <module>
    from .binding.python.porcupine import Porcupine
ImportError: No module named binding.python.porcupine

Going a bit further back.
`python /usr/local/lib/python2.7/dist-packages/pvporcupine/demo/python/porcupine_demo.py --keywords bumblebee`

gives 

listening for:
- bumblebee (sensitivity: 0.500000)
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.front
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround40
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
connect(2) call to /tmp/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
[2019-10-28 13:09:35.485987] detected keyword **(Hooray!)**

(I assume that the various audio device failures are because I'm using the Google AIY voicekit)

However (again), attempting
from pvporcupine.demo.python.porcupine_demo import main
from the python repl fails.

**Comment by mkarliner** [comment]
Off topic (sorry). Is there any licensing tier for small business?

**Comment by kenarsa** [comment]
you have to use python 3 as indicated on PyPI page: https://pypi.org/project/pvporcupine/

for licensing go to picovoice.ai and fill out the page there.

**Comment by mkarliner** [comment]
Thanks for the help. I'm impressed by how well it works!
