### ISSUE TITLE
Support for Raspberry Pi 4

### ISSUE THREAD

**Issue by janeisenmenger** [Picovoice/porcupine#229]
### Expected behaviour
Installing porcupine on a raspberry pi 4 (using raspbian buster) should allow to execute the demo using `pvporcupine_mic --keywords picovoice`

### Actual behaviour
Executing the demo results in the following error message:

```
Traceback (most recent call last):
  File "/home/pi/.local/bin/pvporcupine_mic", line 6, in <module>
    from pvporcupine.demo.python.porcupine_demo import main
  File "/home/pi/.local/lib/python3.7/site-packages/pvporcupine/__init__.py", line 2, in <module>
    from .resources.util.python import *
  File "/home/pi/.local/lib/python3.7/site-packages/pvporcupine/resources/util/python/__init__.py", line 1, in <module>
    from .util import KEYWORDS
  File "/home/pi/.local/lib/python3.7/site-packages/pvporcupine/resources/util/python/util.py", line 63, in <module>
    LIBRARY_PATH = _library_path()
  File "/home/pi/.local/lib/python3.7/site-packages/pvporcupine/resources/util/python/util.py", line 60, in _library_path
    raise NotImplementedError('unsupported platform')
NotImplementedError: unsupported platform
```

### Steps to reproduce the behaviour
Install porcupine via pip:
```
$ pip3 install pvporcupine
$ pvporcupine_mic --keywords picovoice
```

Looking at the source code it's quite obvious that the support for the raspi 4 has not yet been added, see `_RASPBERRY_PI_MACHINES` in `resources/util/python/util.py`

I was hoping to compile libpv_porcupine myself, but couldn't. Any chance this could be added soon?

**Comment by kenarsa** [comment]
we have the intention to add support for rpi4. that being said, I don't have a timeline for it at this point.

**Comment by fabifighter007** [comment]
Is the Pi 4 now supported?

**Comment by ksyeo1010** [comment]
yes.

**Comment by Davideleroe628** [comment]
I’m having the same issue but on raspberry pi 5 :(
Is it going to be supported?

**Comment by kungeplay** [comment]
> I’m having the same issue but on raspberry pi 5 :( Is it going to be supported?

me too on raspberry pi 5
