### ISSUE TITLE
cannot run the python demo application

### ISSUE THREAD

**Issue by Lesleychen** [Picovoice/porcupine#231]
I successfully do 'pip install pvporcupine' in my ubuntu.

Then i follow the guide to run 'pvporcupine_mic --keywords picovoice', but the result is 
Traceback (most recent call last):
  File "/home/yuxiang/.local/bin/pvporcupine_mic", line 7, in <module>
    from pvporcupine.demo.python.porcupine_demo import main
  File "/home/yuxiang/.local/lib/python2.7/site-packages/pvporcupine/__init__.py", line 1, in <module>
    from .binding.python.porcupine import Porcupine
ImportError: No module named binding.python.porcupine

Anyone know how can i solve it and run the demo successfully?

**Comment by kenarsa** [comment]
Use python 3!

**Comment by Lesleychen** [comment]
![image](https://user-images.githubusercontent.com/49524823/67829679-0ba7af80-fb13-11e9-9fb4-75037c916fd2.png)
thanks! I used python3 now , but new problem shows up. Does that mean my computer doesn't have device to support the demo?

**Comment by saravananselvamohan** [comment]
I too got same error in my Ubuntu System while running "pvporcupine_mic --keywords picovoice"
