### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by JoeAteTheBeans** [Picovoice/porcupine#262]
When running any script that has porcupine imported,
`import pvporcupine`
the following error is given :

runfile('C:/Users/JOEWO/OneDrive/Desktop/Programing` Tasks/speech rec/charolotte.py', wdir='C:/Users/JOEWO/OneDrive/Desktop/Programing Tasks/speech rec')
Traceback (most recent call last):

  File "C:\Users\JOEWO\OneDrive\Desktop\Programing Tasks\speech rec\charolotte.py", line 3, in <module>
    import pvporcupine

  File "C:\Users\JOEWO\Anaconda3\lib\site-packages\pvporcupine\__init__.py", line 2, in <module>
    from .resources.util.python import *

  File "C:\Users\JOEWO\Anaconda3\lib\site-packages\pvporcupine\resources\util\python\__init__.py", line 1, in <module>
    from .util import KEYWORDS

  File "C:\Users\JOEWO\Anaconda3\lib\site-packages\pvporcupine\resources\util\python\util.py", line 97, in <module>
    KEYWORD_FILE_PATHS = _keyword_file_paths()

  File "C:\Users\JOEWO\Anaconda3\lib\site-packages\pvporcupine\resources\util\python\util.py", line 90, in _keyword_file_paths
    for x in os.listdir(keyword_files_dir):

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\JOEWO\\Anaconda3\\lib\\site-packages\\pvporcupine\\resources\\util\\python\\../../../resources/keyword_files\\windows'

I am fairly new to python and don't understand what much of this means, but from what I can gather, a file is missing. Was hoping that someone could tell me what's gone wrong here.

I'm running Windows 10 64-bit with Python 3.7.4 (64Bit).

**Comment by kenarsa** [comment]
the PIP package is not supported on Windows as stated in the doc:

https://pypi.org/project/pvporcupine/

**Comment by thomthom** [comment]
> the PIP package is not supported on Windows as stated in the doc:

I would suggest adding a note about that in the README in the PIP section. I also ran into this as I thought it was a quick and easy way to play around. Hadn't gotten to dive into the docs yet - just wanted to run the code examples in the README.
