### ISSUE TITLE
Pi4 Ubuntu 20.04 vanilla pip3 pvporcupine install

### ISSUE THREAD

**Issue by StuartIanNaylor** [Picovoice/porcupine#273]
```
ubuntu@ubuntu:~/porcupine/demo/python$ pvporcupine_mic --keywords picovoice
Traceback (most recent call last):
  File "/usr/local/bin/pvporcupine_mic", line 5, in <module>
    from pvporcupine.demo.python.porcupine_demo_mic import main
  File "/usr/local/lib/python3.8/dist-packages/pvporcupine/__init__.py", line 2, in <module>
    from .resources.util.python import *
  File "/usr/local/lib/python3.8/dist-packages/pvporcupine/resources/util/python/__init__.py", line 1, in <module>
    from .util import KEYWORDS
  File "/usr/local/lib/python3.8/dist-packages/pvporcupine/resources/util/python/util.py", line 43, in <module>
    _PV_SYSTEM, _PV_MACHINE = _pv_platform()
  File "/usr/local/lib/python3.8/dist-packages/pvporcupine/resources/util/python/util.py", line 36, in _pv_platform
    pv_machine = _pv_linux_machine(platform.machine())
  File "/usr/local/lib/python3.8/dist-packages/pvporcupine/resources/util/python/util.py", line 13, in _pv_linux_machine
    model_info = [x for x in cpu_info.split('\n') if 'model name' in x][0]
IndexError: list index out of range
```

**Comment by kenarsa** [comment]
can you run this "cat /proc/cpuinfo" from terminal and paste the result here?

**Comment by StuartIanNaylor** [comment]
```
ubuntu@ubuntu:~$ cat /proc/cpuinfo
processor       : 0
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 1
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 2
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 3
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

Hardware        : BCM2835
Revision        : b03111
Serial          : 10000000c6e9e69d
Model           : Raspberry Pi 4 Model B Rev 1.1
```

**Comment by kenarsa** [comment]
it seems like the new ubuntu changed the output and our logic for picking the CPU type doesn't work on this specific version of ubuntu. this is something we can look at for subsequent release.

for now, you have two options (1) clone repo directly (2) use an older version of ubuntu or use a raspbian

**Comment by StuartIanNaylor** [comment]
I will use Raspbian for now, the 64bit Ubuntu is likely to be of much interest as with the Pi4 it actually has some substantial performance gains.
So clone compile and it should work? Or clone compile and hack a little and it should work?

**Comment by kenarsa** [comment]
clone and follow the instructions here: https://github.com/Picovoice/porcupine#repository

**Comment by kenarsa** [comment]
We clarified that the PIP works on Raspberry Pi running Raspbian in v1.8. For other OSes on RPI the repo method probably will be the robust way to go.
