### ISSUE TITLE
Pi4 Ubuntu 20.10 groovy: after porcupine installation, import pvporcupine fails!

### ISSUE THREAD

**Issue by fabiuslongo** [Picovoice/porcupine#328]
After "pip install pvporcupine"

### Expected behaviour

>>> import pvporcupine
>>>

### Actual behaviour

>>> import pvporcupine
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fabio/porcupine/lib/python3.8/site-packages/pvporcupine/__init__.py", line 13, in <module>
    from .util import *
  File "/home/fabio/porcupine/lib/python3.8/site-packages/pvporcupine/util.py", line 54, in <module>
    _PV_SYSTEM, _PV_MACHINE = _pv_platform()
  File "/home/fabio/porcupine/lib/python3.8/site-packages/pvporcupine/util.py", line 47, in _pv_platform
    pv_machine = _pv_linux_machine(platform.machine())
  File "/home/fabio/porcupine/lib/python3.8/site-packages/pvporcupine/util.py", line 24, in _pv_linux_machine
    model_info = [x for x in cpu_info.split('\n') if 'model name' in x][0]
IndexError: list index out of range

---------------------------------------------------------------------

I know a similar issue (closed) exists, but, excluding the installation of an older ubuntu version, the other solution lead me to the same error above. Can you give more detailed instructions? Thanks.

**Comment by kenarsa** [comment]
We only support Raspbian for RPI. If you switch to Raspbian it should work out of the box. Ubuntu seems to be a popular choice now so I keep this open as a possible enhancement for future releases. For now, you can either:

1- Switch to Raspbian
2- Clone the repo instead of trying to use the PIP package.

**Comment by fabiuslongo** [comment]
I would go on with the option 2... but a setup.py is missing in the repository root, for installing the package without the usage of PIP. Now, I'm not an expert of Python... so, could you please provide the steps for a proper installation? Thanks

**Comment by fabiuslongo** [comment]
Okay, I've changed porcupine/binding/python/utils.py in a way which return the proper platform (cortex-a72). Now, there's a new issue, I suppose (after processed setup.py) :

>>> import pvporcupine
>>> handle = pvporcupine.create(keywords=['picovoice'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fabio/porcupine/binding/python/pvporcupine/__init__.py", line 64,                         in create
    return Porcupine(
  File "/home/fabio/porcupine/binding/python/pvporcupine/porcupine.py", line 60,                         in __init__
    library = cdll.LoadLibrary(library_path)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/fabio/porcupine/binding/python/pvporcupine/lib/raspberry-pi/cortex-a72/libpv_porcupine.so: wrong ELF class: ELFCLASS32

---------------------------------------------------------

I suppose this means libpv_porcupine.so is only for 32bit platform. Is that right?

**Comment by kenarsa** [comment]
That's odd! Can you please try to run the C demo on your RPI? https://github.com/Picovoice/porcupine/tree/master/demo/c#file-demo

This should be really easy. The reason I want you to do it is that this uses the same .so file. So it will help debug the process.

**Comment by kenarsa** [comment]
closing due to inactivity
