### ISSUE TITLE
Porcupine Issue: AARCH64 is not supported, even though ARM32 binaries should have backwards compatibility

### ISSUE THREAD

**Issue by 2231puppy** [Picovoice/porcupine#349]
### Expected behaviour
Porcupine will run on a RPi 4B 4GB RAM with the AARCH64 beta

### Actual behaviour
Porcupine does not run on a RPi 4B 4GB RAM with the AARCH64 beta, with the following error:

`Traceback (most recent call last):
  File "/usr/local/bin/porcupine_demo_mic", line 6, in <module>
    from pvporcupinedemo.porcupine_demo_mic import main
  File "/usr/local/lib/python3.7/dist-packages/pvporcupinedemo/porcupine_demo_mic.py", line 19, in <module>
    import pvporcupine
  File "/usr/local/lib/python3.7/dist-packages/pvporcupine/__init__.py", line 13, in <module>
    from .util import *
  File "/usr/local/lib/python3.7/dist-packages/pvporcupine/util.py", line 54, in <module>
    _PV_SYSTEM, _PV_MACHINE = _pv_platform()
  File "/usr/local/lib/python3.7/dist-packages/pvporcupine/util.py", line 47, in _pv_platform
    pv_machine = _pv_linux_machine(platform.machine())
  File "/usr/local/lib/python3.7/dist-packages/pvporcupine/util.py", line 24, in _pv_linux_machine
    model_info = [x for x in cpu_info.split('\n') if 'model name' in x][0]
IndexError: list index out of range
`

### Steps to reproduce the behaviour
Run the demo on a RPi 4B 4GB RAM with the AARCH64 beta

**Comment by kenarsa** [comment]
This is yet a beta version. We only support the official one at the moment with is the 32-bit Raspbian. Once this becomes an official release we will support it.
