### ISSUE TITLE
Porcupine Issue: IndexError @import on Raspberry Pi 4

### ISSUE THREAD

**Issue by wgruenberger** [Picovoice/porcupine#356]
### Expected behaviour
install and import pvporcupine-1.9.0 on a raspberry pi 4

### Actual behaviour
IndexError: list index out of range
@import in python3:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/w/.local/lib/python3.7/site-packages/pvporcupine/__init__.py", line 13, in <module>
    from .util import *
  File "/home/w/.local/lib/python3.7/site-packages/pvporcupine/util.py", line 54, in <module>
    _PV_SYSTEM, _PV_MACHINE = _pv_platform()
  File "/home/w/.local/lib/python3.7/site-packages/pvporcupine/util.py", line 47, in _pv_platform
    pv_machine = _pv_linux_machine(platform.machine())
  File "/home/w/.local/lib/python3.7/site-packages/pvporcupine/util.py", line 24, in _pv_linux_machine
    model_info = [x for x in cpu_info.split('\n') if 'model name' in x][0]
IndexError: list index out of range

### Steps to reproduce the behaviour
install via pip3:
pip3 install --user --upgrade pvporcupine                                                                                           
...
Successfully installed pvporcupine-1.9.0

open python3 shell
`import pvporcupine`

**Comment by dbartle** [comment]
Are you using Raspberry Pi OS 32-bit, or the 64-bit preview/beta? Only the 32-bit is presently supported.

**Comment by wgruenberger** [comment]
> Are you using Raspberry Pi OS 32-bit, or the 64-bit preview/beta? Only the 32-bit is presently supported.

that's it, i use the 64-bit version thank you!
