### ISSUE TITLE
OSError: [Errno -9981] Input overflowed

### ISSUE THREAD

**Issue by devjewel01** [Picovoice/porcupine#423]
### Please help me
Assistant is listening....
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/Robot-Blueberry/src/main.py", line 294, in picovoice_run
    pcm = audio_stream.read(porcupine.frame_length)
  File "/home/pi/env/lib/python3.7/site-packages/pyaudio.py", line 608, in read
    return pa.read_stream(self._stream, num_frames, exception_on_overflow)
OSError: [Errno -9981] Input overflowed
..
**What is OSError?**

**Comment by kenarsa** [comment]
closing this issue as it does not follow the instructions in the issue template. the template explicitly asks for instructions to reproduce the issue!
