### ISSUE TITLE
DLL for JNI Integration on non-linux machines?

### ISSUE THREAD

**Issue by tatanpoker09** [Picovoice/Porcupine#45]
As of now, I want to integrate Porcupine with Java through JNI, as you know this means that the dll must be built specifically for JNI Integration (through JNI Wrappers)
```
JNIEXPORT void JNICALL Java_package_name_ClassName_methodName(JNIEnv* env, jobject thiz) {}
```
I have only found this wrappers in android's .so libs, but because I want to implement it in Java, I cannot implement it on a Windows PC. I am using an AMD64 arch. Is there any way I can build this on my own? If not, could you provide me the modified dll?

**Comment by kenarsa** [comment]
https://github.com/Picovoice/Porcupine/tree/master/demo/android

**Comment by tatanpoker09** [comment]
But the binary files it uses are .so, I need .dll files in order to work with windows. Problem is, that .so is modified from the original in order to meet the required wrapping, you can see that in the next picture
![image](https://user-images.githubusercontent.com/6262015/42196602-dc5ee462-7e4c-11e8-9e0b-9b699d8cf50c.png)

**Comment by kenarsa** [comment]
Got it. You don't want an Android build. Just want a JNI interface. I think you can use the ".a" files under lib/windows with your own JNI file and then build a ".dll" from them. Apologies for the confusion.

**Comment by tatanpoker09** [comment]
I can't seem to modify them in any way, I'll try linking them to another c++ "wrapper program", with the wrapping methods and just a call inside.

**Comment by tatanpoker09** [comment]
Alright, so after finally being able to build a succesful .dll with a JNI interface, I am encountering this error, which is directly linked to the dll.
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000067641f65, pid=1040, tid=0x0000000000000ee8
#
# JRE version: Java(TM) SE Runtime Environment (8.0_161-b12) (build 1.8.0_161-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.161-b12 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [libpv_porcupine.dll+0x1f65]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# D:\Programming\Game Development\PorcupineManager\hs_err_pid1040.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```
This is how it is being called from Java:
```java
public Porcupine(
            String modelFilePath,
            String keywordFilePath,
            float sensitivity) throws PorcupineException {
        numberKeywords = 1;
        System.out.println("Sensitivity: "+sensitivity);
        System.out.println("Modelfilepath: "+modelFilePath);
        System.out.println(keywordFilePath);
        System.out.println("==================");
        try {
            object = init(modelFilePath, new String[]{keywordFilePath}, new float[]{sensitivity});
        } catch (Exception e) {
            throw new PorcupineException(e);
        }
    }
```
And this is in C:
```c++
 JNIEXPORT jlong JNICALL Java_ai_picovoice_porcupine_Porcupine_init(JNIEnv *env, jobject thisObj, jstring str, jobjectArray objArray, jfloatArray floatArray){
    jfloat *body = (*env)->GetFloatArrayElements(env, floatArray, 0);
    const char *modelFilePath = (*env)->GetStringUTFChars(env, str, 0);
    int modelCount = (*env)->GetArrayLength(env, objArray);
    printf("Sensitivity: ");
    printf("%f \n", body[0]);
    printf("Modelfilepath: %s \n", modelFilePath);
    const char *keyfilepaths[modelCount];
    for (int i=0; i<modelCount; i++) {
      jstring string = (jstring) (*env)->GetObjectArrayElement(env, objArray, i);
      const char *keyfilepath = (*env)->GetStringUTFChars(env, string, 0);
      keyfilepaths[i] = keyfilepath;
        (*env)->ReleaseStringUTFChars(env, string, keyfilepath);
        printf("KeywordFile: %s", keyfilepaths[i]);
    }
    pv_porcupine_multiple_keywords_init(modelFilePath, modelCount, keyfilepaths, body, object);
      (*env)->ReleaseFloatArrayElements(env, floatArray, body, 0);
      (*env)->ReleaseStringUTFChars(env, str, modelFilePath);
    return object;
  }
```

Please help, I seriously don't know anymore.

**Comment by zsmaguc** [comment]
I put this together, without any knowledge of c/c++. It works, but there is no error handling and there are probably some other mistakes.

It would be nice if Porcupine team shared their implementation of native JNI functions from the Android demo project.

```cpp
#include "ai_picovoice_porcupine_Porcupine.h"
#include "../include/picovoice.h"
#include "../include/pv_porcupine.h"
#include <jni.h>
#include <string.h>
#include <iostream>

using namespace std;

//TODO: error handling

JNIEXPORT jint JNICALL Java_ai_picovoice_porcupine_Porcupine_getFrameLength(JNIEnv *env, jobject obj) {
    return pv_porcupine_frame_length();
}

JNIEXPORT jint JNICALL Java_ai_picovoice_porcupine_Porcupine_getSampleRate(JNIEnv *env, jobject obj) {
    return pv_sample_rate();
}

JNIEXPORT jlong JNICALL Java_ai_picovoice_porcupine_Porcupine_init(JNIEnv *env, jobject obj, jstring modelFile, jobjectArray keywordFiles, jfloatArray sensitivities) {
    long object = 0;
    pv_porcupine_object_t *result = (pv_porcupine_object_t *) &object;

    jclass thisClass = env->GetObjectClass(obj);
    jfieldID fidNumber = env->GetFieldID(thisClass, "numberKeywords", "I");
    jint numberKeywords = env->GetIntField(obj, fidNumber);

    const char *ckwFiles[numberKeywords];
    for (int i=0; i<numberKeywords; i++) {
        jstring jkwFile = (jstring) env->GetObjectArrayElement(keywordFiles, i);
        const char *ckwFile = env->GetStringUTFChars(jkwFile, NULL);
        ckwFiles[i] = strdup(ckwFile);
        env->ReleaseStringUTFChars(jkwFile, ckwFile);
        env->DeleteLocalRef(jkwFile);
    }

    const char *modelFileCStr = env->GetStringUTFChars(modelFile, NULL);
    jfloat *senBody = env->GetFloatArrayElements(sensitivities, 0);

    pv_porcupine_multiple_keywords_init(modelFileCStr, numberKeywords, ckwFiles, senBody, &result);

    env->ReleaseFloatArrayElements(sensitivities, senBody, 0);
    env->ReleaseStringUTFChars(modelFile, modelFileCStr);

    return (jlong) result;
}

JNIEXPORT jint JNICALL Java_ai_picovoice_porcupine_Porcupine_process(JNIEnv *env, jobject obj, jlong porcupineObject, jshortArray pcm) {
    int result;

    jshort *body = env->GetShortArrayElements(pcm, 0);

    pv_porcupine_multiple_keywords_process((pv_porcupine_object_t *) porcupineObject, body, &result);

    env->ReleaseShortArrayElements(pcm, body, 0);

    return result;
}

JNIEXPORT void JNICALL Java_ai_picovoice_porcupine_Porcupine_delete(JNIEnv *env, jobject obj, jlong porcupineObject) {
    pv_porcupine_delete((pv_porcupine_object_t *) porcupineObject);
}
```

**Comment by tatanpoker09** [comment]
@zsmaguc Same error is happening, do you think you can provide me the dll you got from that code?

**Comment by zsmaguc** [comment]
Win x64
[libjni.zip](https://github.com/Picovoice/Porcupine/files/2169279/libjni.zip)

**Comment by tatanpoker09** [comment]
You just saved my life, I love you <3

**Comment by cogmeta** [comment]
@tatanpoker09 Please help. I am getting following error

exception in thread "main" java.lang.UnsatisfiedLinkError: C:\xxx\porcupine_java\ai\picovoice\porcupine\jni\libjni.dll: Can't find dependent libraries
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.lang.System.loadLibrary(Unknown Source)
        at ai.picovoice.porcupine.Porcupine.<clinit>(Porcupine.java:29)

I have following libs in ./jni folder


20-02-2019  10:25    <DIR>          ..
19-02-2019  23:10            51,330 libjni.dll
19-02-2019  22:49           141,942 libpv_porcupine.dll
19-03-2017  02:27           632,800 msvcrt.dll
