### ISSUE TITLE
Seeking help to get porcupine work on Mac OS 10.13

### ISSUE THREAD

**Issue by thevickypedia** [Picovoice/porcupine#467]
**NOT AN ISSUE**

Hello,

First of all, kudos on the great application you have built. This is the first simple yet powerful library I found for keyword detection.

I tested out this application on Mac OS 10.15.* using a `pip` install and it works just as it should. I replicated the same on my iMac running Mac OS 10.13.* where I keep getting `OSError` from `ctypes` module. I figured this isn't an issue with `porcupine` itself.

I tried using `install_name_tool` to change the reference of the `.dylib` but no luck.

I followed some earlier issues and found one of the devs have actually used this on Mac OS 10.13.* 
I'm curious how I can install this module on Mac OS High Sierra. Can you please let me know if that can be done with an alternate way of installation or an older version would help.

https://github.com/Picovoice/Porcupine/issues/39

###### Traceback:
```
iMac:~ vicky$ porcupine_demo_mic --keywords alexa
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/porcupine_demo_mic", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pvporcupinedemo/porcupine_demo_mic.py", line 201, in main
    PorcupineDemo(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pvporcupinedemo/porcupine_demo_mic.py", line 84, in run
    porcupine = pvporcupine.create(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pvporcupine/__init__.py", line 64, in create
    return Porcupine(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pvporcupine/porcupine.py", line 60, in __init__
    library = cdll.LoadLibrary(library_path)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pvporcupine/lib/mac/x86_64/libpv_porcupine.dylib, 6): Symbol not found: ____chkstk_darwin
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pvporcupine/lib/mac/x86_64/libpv_porcupine.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pvporcupine/lib/mac/x86_64/libpv_porcupine.dylib
```

**Comment by kenarsa** [comment]
Thanks! we will address this in the coming weeks. The `.dylib` is built to run on 10.15 and later. just curious, why not update to the latest macOS?

**Comment by thevickypedia** [comment]
Thanks for the response. The iMac is a 2011 model running High Sierra. It's hardware doesn't support an upgrade 😞

**Comment by kenarsa** [comment]
hey - unfortunately this doesn't seem to be making it to our immediate roadmap. I keep this in mind for the future if we can make dev time.

**Comment by thevickypedia** [comment]
@kenarsa Thanks for the intimation. I have upgraded my Mac and got it working fine but still will keep an eye around, I'm curious.
