### ISSUE TITLE
Can't integrate Porcupine into python

### ISSUE THREAD

**Issue by fredrikj31** [Picovoice/Porcupine#54]
I tried to integrate it into python but i got this error:

```
Traceback (most recent call last):
  File "SpeechRecognition.py", line 14, in <module>
    handle = Porcupine(library_path, model_file_path, keyword_file_paths=keyword_file_paths, sensitivities=sensitivities)
NameError: name 'Porcupine' is not defined
```

And this is my code:

```
# WAKE WORD
library_path = ['WakeWord/lib/${SYSTEM}/${MACHINE}/']
model_file_path = ['WakeWord/lib/common/porcupine_params.pv']
keyword_file_paths = ['WakeWord/resources/keyword_files/alexa_windows.ppn']
sensitivities = [0.5, 0.4]
handle = Porcupine(library_path, model_file_path, keyword_file_paths=keyword_file_paths, sensitivities=sensitivities)
# WAKE WORD END

def get_next_audio_frame():
    pass

while True:
    pcm = get_next_audio_frame()
    keyword_index = handle.process(pcm)
    if keyword_index >= 0:
        # detection event logic/callback
        pass
```
(Just the default from github)

- Fredrik :)

**Comment by kenarsa** [comment]
You need to import the Porcupine class. Have a look at the Python demo here and hopefully it will clear things up: https://github.com/Picovoice/Porcupine/blob/master/demo/python/porcupine_demo_offline.py

**Comment by fredrikj31** [comment]
How do you mean about that. I tried to do this ```from porcupine import Porcupine``` but i don't know if that's the right way to do it. Sorry i'm a lille new to python

**Comment by kenarsa** [comment]
that is correct. also, you need to make sure the file containing the definition of Porcupine is in your sys path. If you read the beginning of the link of the demo I've sent above I think it all will make sense.

**Comment by fredrikj31** [comment]
I can't figure it out... Is there a tutorial how to do it... Maybe a video or something? @kenarsa (Just so you don't have to write what i need to do) :)

**Comment by fredrikj31** [comment]
I now have this problem because i tried to integrate it into my code...

This is my code:
```
# WAKE WORD
import sys
import soundfile
import os

sys.path.append(os.path.join(os.path.dirname(__file__), 'WakeWord/binding/python/porcupine.py'))

library_path = 'WakeWord/lib/windows/amd64/'
model_file_path = 'WakeWord/lib/common/porcupine_params.pv'
keyword_file_paths = 'WakeWord/resources/keyword_files/alexa_windows.ppn'
sensitivities = [0.5, 0.4]
handle = Porcupine(library_path, model_file_path, keyword_file_paths=keyword_file_paths, sensitivities=sensitivities)
# WAKE WORD END

def get_next_audio_frame():
    pass

while True:
    pcm = get_next_audio_frame()
    keyword_index = handle.process(pcm)
    if keyword_index >= 0:
        # detection event logic/callback
        pass
``` 

And this is my error:
```
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    handle = Porcupine(library_path, model_file_path, keyword_file_paths=keyword_file_paths, sensitivities=sensitivities)
NameError: name 'Porcupine' is not defined
```

- Fredrik

**Comment by kenarsa** [comment]
you still need to import it. add:
**from porcupine import Porcupine** 
after **sys.path.append(**

would be nice if you can make a video tutorial after this and share your learnings with the community.

**Comment by fredrikj31** [comment]
I tried to put it over it... But I got this error:

```
Traceback (most recent call last):
  File "Test.py", line 8, in <module>
    from porcupine import Porcupine
ModuleNotFoundError: No module named 'porcupine'
```

**Comment by kenarsa** [comment]
my guess is that the path here is not set correctly:

sys.path.append(os.path.join(os.path.dirname(__file__), 'WakeWord/binding/python/porcupine.py'))

print the result of join and see if it is a valid path

**Comment by fredrikj31** [comment]
I fixed the file... But now got this error:
```
Traceback (most recent call last):
  File "Test.py", line 22, in <module>
    handle = Porcupine(library_path, model_file_path, keyword_file_paths=keyword_file_paths, sensitivities=sensitivities)
  File "WakeWord/binding/python\porcupine.py", line 69, in __init__
    library = cdll.LoadLibrary(library_path)
  File "C:\Python\lib\ctypes\__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

What can I do to fix that problem? @kenarsa

**Comment by kenarsa** [comment]
it is hard to say from the information you provided ...
