### ISSUE TITLE
Porcupine Issue: UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH in "libpv_porcupine.so" (built with --hash-style=gnu?)

### ISSUE THREAD

**Issue by josefeliuf** [Picovoice/porcupine#615]
I haven't found this error on the documentation. (basically nowhere)

### Expected behaviour

Run android demo and work properly

### Actual behaviour

Error pressing start button (the app crashes) with the following stacktrace:

2022-01-10 12:09:31.910 17155-17155/com.example.androidforegroundservice E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.androidforegroundservice, PID: 17155
    java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH in "libpv_porcupine.so" (built with --hash-style=gnu?)
        at java.lang.Runtime.loadLibrary(Runtime.java:364)
        at java.lang.System.loadLibrary(System.java:526)
        at ai.picovoice.porcupine.Porcupine.<clinit>(Porcupine.java:48)
        at ai.picovoice.porcupine.Porcupine$Builder.build(Porcupine.java:258)
        at ai.picovoice.porcupine.PorcupineManager$Builder.build(PorcupineManager.java:161)
        at ai.picovoice.porcupinedemoservice.PorcupineService.onStartCommand(PorcupineService.java:80)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2809)
        at android.app.ActivityThread.access$2100(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1340)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5375)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:989)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
        at dalvik.system.NativeStart.main(Native Method)

### Steps to reproduce the behaviour

- Install the android demo
- Open the app
- Press start button
- app crashes

I must say that i am working on a kitkat device (android 4.4 version). I do have internet connection (via sim card, 4g) and microphone permission.

**Comment by kenarsa** [comment]
what's the actual device? this makes it easier to look into this...

**Comment by laves** [comment]
@josefeliuf - thanks for the report. We've identified the issue, which affects older versions of Android, and are going to release a patch ASAP.

**Comment by josefeliuf** [comment]
You are welcome!  :)

**Comment by laves** [comment]
@josefeliuf - we've just patched this issue with #618. Package porcupine-android:2.0.2 should not throw this error for Android 4.4.

I notice you're using the Service demo - FYI, this demo is not fully featured for Android 4.4. Porcupine will work, but you will not see the popup notifications when it detects the keyword as that is only supported on 8.0 and higher.

**Comment by josefeliuf** [comment]
Okay thanks for letting me know! have a nice day
