### ISSUE TITLE
dotnet\PorcupineDemo\MicDemo.Release: [ERROR] failed to parse AccessKey

### ISSUE THREAD

**Issue by ibebbs** [Picovoice/porcupine#625]
I have been trying to get started with Porcupine for .NET but no matter what I try, I can't get my access key to work. I ended up resorting to cloning the `dotnet\PorcupineDemo` sample but when running the command below (obviously with '[redacted]' replaced by the correct portion of the key) I _still_ get the "failed to parse AccessKey":

```
dotnet run -c MicDemo.Release -- --access_key F4w4sE[redacted]Ug== --keywords porcupine
```

I've tried various formats of access key, delimiting it in quotes and curly braces, etc. all to no avail. I can confirm internet access and that I'm able to use wake word detection in Picovoice Console.

Any suggestions? This is driving me nuts...

### Expected behaviour
MicDemo.Release should run

### Actual behaviour
```
PS :> dotnet run -c MicDemo.Release -- --access_key F4w4sE[redacted]Ug== --keywords porcupine
[ERROR] failed to parse AccessKey 'F4w4sE[redacted]Ug=='
```

### Steps to reproduce the behaviour
1. Generate an access key in the Picovoice Console
2. Attempt to run `dotnet\PorcupineDemo\MicDemo.Release` using the new access key.

### Environment ###
Installed Dotnet SDKs: 2.1.811, 2.2.207, 3.1.100, 3.1.404, 5.0.201, 5.0.404, 6.0.101
Nuget Package: [2.0.1](https://www.nuget.org/packages/Porcupine/2.0.1)

### Other Info ###
* Same error while trying to instantiate Rhino: 
    ```
    Rhino rhino = Rhino.Create("F4w4sE[redacted]Ug==", "${ContextFile}");
    ```
* Forcing the use of .netcore 3.1[.404] (via global.json) results in same error.

**Comment by laves** [comment]
@ibebbs silly question - are you sure you copied it correctly from Picovoice Console? I see an AccessKey in our database that contains the partial string you posted, but starts with a different character.

**Comment by laves** [comment]
Hope that solved your problem! Closing due to inactivity.

**Comment by ibebbs** [comment]
Hey @laves ,

Firstly, my most profound, humble and abject apologies for the red herring; the access key I was using above was indeed wrong. However, even with the correct access key, both my own project and `MicDemo` still fail to run.

In the first instance, by following the steps in the [.NET Quick Start](https://picovoice.ai/docs/quick-start/porcupine-dotnet/) I created a new (.NET 6.0) project and added a reference to the Porcupine package as shown below:

```
mkdir PicoVoiceSpike
cd PicoVoiceSpike
dotnet new console
dotnet add package Porcupine
```

I then modified `Program.cs` to:

```
using Pv;

Porcupine porcupine = Porcupine.FromBuiltInKeywords("VF4w4sE[redacted]Ug==", new List<BuiltInKeyword> { BuiltInKeyword.PORCUPINE, BuiltInKeyword.BUMBLEBEE });

Console.WriteLine("Successfully instantiated Porcupine");
```

Then:

```
dotnet build
dotnet run
No Instance(s) Available.
Unhandled exception. Pv.PorcupineActivationException: Porcupine init failed.
   at Pv.Porcupine..ctor(String accessKey, IEnumerable`1 keywordPaths, String modelPath, IEnumerable`1 sensitivities)
   at Pv.Porcupine.FromBuiltInKeywords(String accessKey, IEnumerable`1 keywords, String modelPath, IEnumerable`1 sensitivities)
   at Program.<Main>$(String[] args) in S:\Source\Spikes\PicoVoiceSpike\Program.cs:line 3
```

Similarly, with fresh clone of the [Porcupine Repository](https://github.com/Picovoice/porcupine), the MicDemo fails with the same exception:

```
dotnet run -c MicDemo.Release -- --access_key VF4w4sE[redacted]Ug== --keywords porcupine
Pv.PorcupineActivationException: Porcupine init failed.
   at Pv.Porcupine..ctor(String accessKey, IEnumerable`1 keywordPaths, String modelPath, IEnumerable`1 sensitivities)
   at Pv.Porcupine.FromKeywordPaths(String accessKey, IEnumerable`1 keywordPaths, String modelPath, IEnumerable`1 sensitivities)
   at PorcupineDemo.MicDemo.RunDemo(String accessKey, String modelPath, List`1 keywordPaths, List`1 sensitivities, Int32 audioDeviceIndex, String outputPath) in S:\Source\External\porcupine\demo\dotnet\PorcupineDemo\MicDemo.cs:line 56
   at PorcupineDemo.MicDemo.Main(String[] args) in S:\Source\External\porcupine\demo\dotnet\PorcupineDemo\MicDemo.cs:line 291
```

So, am I doing something else crazy silly?

Thanks for your help.

**Comment by laves** [comment]
@ibebbs - we looked into this and it could be related to issue #617, which we're currently working on fixing in the upcoming release.  In rare cases, we've seen Windows devices failing to activate. Could you run the following command in Powershell and tell us if it returns a valid UUID or something else?
```powershell
(Get-CimInstance -Class Win32_ComputerSystemProduct).UUID
```

**Comment by ibebbs** [comment]
Hi @laves,

Apologies for the delay in getting back to you.

So, interesting development: On my development machine the command you supplied returns nothing when run from Powershell:

```
PS C:\> (Get-CimInstance -Class Win32_ComputerSystemProduct).UUID
PS C:\>
```

But on my laptop it does indeed return a GUID:

```
PS C:\> (Get-CimInstance -Class Win32_ComputerSystemProduct).UUID
[<A valid GUID>]
PS C:\>
```

Hope that helps. Is there anything I can do (additional settings / environment variables) to work around this issue?

Thanks!

**Comment by laves** [comment]
Thanks for getting back to us - this is helpful. Can you try the recently released Porcupine v2.1? Nuget package should be version `2.1.0`. We may have already addressed your issue with this release, however, we're still planning on releasing a Windows specific patch in the coming weeks.

**Comment by ibebbs** [comment]
I'm afraid I am already using v2.1[.0] and encountering the error (I also tried downgrading to 2.0.1 - no joy).

Let me know if you need testers for a pre-release package.

**Comment by laves** [comment]
@ibebbs - we're currently in the process of rolling out the patch. Can you try the Porcupine NuGet package v2.1.1 and let us know if it's addressed your issue?

**Comment by ibebbs** [comment]
Worked like a charm @laves thanks. Coupled with PvRecorder I now have wake word detection working...
