### ISSUE TITLE
Porcupine Issue: syntax error raised when running porcupine_demo_mic

### ISSUE THREAD

**Issue by Bazmundi** [Picovoice/porcupine#649]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
Unknown, code does not run

### Actual behaviour

With environment variable ACCESS_KEY set to access key from picovoice account and with network access available.

```
$ porcupine_demo_mic --access_key ${ACCESS_KEY} --keywords porcupine
Traceback (most recent call last):
  File "/usr/local/bin/porcupine_demo_mic", line 6, in <module>
    from pvporcupinedemo.porcupine_demo_mic import main
  File "<fstring>", line 1
    (self._access_key=)
                     ^
SyntaxError: invalid syntax


```

With access code encoded in command

```
$ porcupine_demo_mic --access_key O6m<redacted middle of access code>4fg== --keywords porcupine
Traceback (most recent call last):
  File "/usr/local/bin/porcupine_demo_mic", line 6, in <module>
    from pvporcupinedemo.porcupine_demo_mic import main
  File "<fstring>", line 1
    (self._access_key=)
                     ^
SyntaxError: invalid syntax

```

### Steps to reproduce the behaviour

Running on hyproit on RPi 3B+ which comes with python 3.7.3
Installed pvporcupine as per destructions at: https://picovoice.ai/docs/quick-start/porcupine-python/

Tried example python code but could not resolve issues I was finding it would not resolve the env to pick up the access key.

```
$ python
Python 3.7.3 (default, Dec 20 2019, 18:57:59)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pvporcupine
>>> porcupine = pvporcupine.create(
...   access_key='${ACCESS_KEY}',
...   keywords=['picovoice', 'bumblebee']
... )
[ERROR] failed to parse AccessKey '${ACCESS_KEY}'
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/usr/local/lib/python3.7/dist-packages/pvporcupine/__init__.py", line 82, in create
    sensitivities=sensitivities)
  File "/usr/local/lib/python3.7/dist-packages/pvporcupine/porcupine.py", line 158, in __init__
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]()
pvporcupine.porcupine.PorcupineInvalidArgumentError
>>>
```
Worked fine with access key embedded in code, except the python code example was obviously stunted and not a full example.

Opted into using the demo at https://picovoice.ai/docs/quick-start/porcupine-python/#demo and so then arrived at the syntax error reported at the top.

Uninstalled everything then reinstalled but now get:

```
HypriotOS/armv7: pirate@silver-pearl in ~
$ porcupine_demo_mic --access_key ${ACCESS_KEY} --keywords porcupine
-bash: /usr/local/bin/porcupine_demo_mic: No such file or directory
HypriotOS/armv7: pirate@silver-pearl in ~
$ porcupine_demo_mic --access_key O6mlLw<redacted middle of key>ujA//WcHJ8w4fg== --keywords porcupine
-bash: /usr/local/bin/porcupine_demo_mic: No such file or directory
HypriotOS/armv7: pirate@silver-pearl in ~
$ porcupine_demo_mic --help
-bash: /usr/local/bin/porcupine_demo_mic: No such file or directory
HypriotOS/armv7: pirate@silver-pearl in ~
```

**Comment by kenarsa** [comment]
`${ACCESS_KEY)}` is not meant to be an environment variable is a template for you to change with your own AccessKey. I cannot reproduce this issue. What is the version of `pvporcupinedemo` you are using? You can run this command to get them:

```console
pip3 freeze | grep pvporcupine
```

**Comment by Bazmundi** [comment]
> `${ACCESS_KEY)}` is not meant to be an environment variable is a template for you to change with your own AccessKey. I cannot reproduce this issue. What is the version of `pvporcupinedemo` you are using? You can run this command to get them:
> 
> ```
> pip3 freeze | grep pvporcupine
> ```

Ah, "meant to be" but using apparently "syntax", very good.

Ignore the env aspect please, as I have been using the key in the command line.  

If I have only pipped as of the date above I assume its the latest version?

```
$ pip3 freeze | grep pvporcupinedemo
pvporcupinedemo==2.1.0
```

**Comment by Bazmundi** [comment]
What may help is I tried the demo:

```
porcupine_demo_file --access_key ${ACCESS_KEY} --input_audio_path ${AUDIO_PATH} --keywords grasshopper porcupine

```

I did this by using Audacity to make a 16000 sample rate wave with a range of spoken words, including `grasshopper` and `porcupine`, on my PC and uploaded to my RPi.

That `porcupine_demo_file` example ran fine ???!?!!??

**Comment by kenarsa** [comment]
Got it. Can you try this on Raspbian? If you can reproduce it on Raspbain then I can look into it more closely. Keep in mind that we don't have support for the OS you are using so it's hard for me to figure out what is the issue here.

**Comment by Bazmundi** [comment]
> Got it. Can you try this on Raspbian? If you can reproduce it on Raspbain then I can look into it more closely. Keep in mind that we don't have support for the OS you are using so it's hard for me to figure out what is the issue here.

Yep. Will try to reproduce on Raspian.  

If I need hack at the code to get it working on hypriot, have you any best guesses at the mo?

**Comment by Bazmundi** [comment]
So, I burned onto an SD:

```
Raspberry Pi OS Lite
Release date: October 30th 2021
Kernel version: 5.10
```
Setup wifi and ssh so I could get files from my PC (test.wav for example).

Ran:
```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get python3-pip
sudo pip3 install pvporcupinedemo
```

Python version that comes with:
```
pi@raspberrypi:~ $ python --version
Python 3.9.2
```

As for previous report, the demo versus the wav file worked.
So this time did:

```
porcupine_demo_mic --access_key O6mlLwkDR8A<redact middle of key>jA//WcHJ8w4fg== --keywords porcupine --audio_device_index 1
```

So is this the difference between Python 3.7.3 that came with hypriot and the 3.9.2 that comes with RPi OS Lite?

**Comment by Bazmundi** [comment]
Okay, I bumbled through and installed python 3.9.2 onto my hypriot.  Ripped out pvporcupinedemo and then pipped it back in with 3.9.2.

Given the problem reported at: https://github.com/Picovoice/porcupine/issues/653

I am now getting the following: 

```
$ porcupine_demo_mic --access_key O6mlLwkDR8A306FN<redacted middle of key>WcHJ8w4fg== --keywords porcupine --audio_device_index 1
AccessKey 'O6mlLwkDR8A306FNQKC/2gb/J9k5soyHJZvcybBrujA//WcHJ8w4fg==' has reached it's temporary device limit
Traceback (most recent call last):
  File "/usr/local/bin/porcupine_demo_mic", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/pvporcupinedemo/porcupine_demo_mic.py", line 219, in main
    PorcupineDemo(
  File "/usr/local/lib/python3.9/site-packages/pvporcupinedemo/porcupine_demo_mic.py", line 128, in run
    raise e
  File "/usr/local/lib/python3.9/site-packages/pvporcupinedemo/porcupine_demo_mic.py", line 83, in run
    porcupine = pvporcupine.create(
  File "/usr/local/lib/python3.9/site-packages/pvporcupine/__init__.py", line 77, in create
    return Porcupine(
  File "/usr/local/lib/python3.9/site-packages/pvporcupine/porcupine.py", line 158, in __init__
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]()
pvporcupine.porcupine.PorcupineActivationLimitError
```
So, given the syntax error under 3.7.3 was in and around importing of the key, its tempting to assume the bump to 3.9.2 fixed the problem BUT won't know until I sort out that inadvertent activation limit issue.

**Comment by kenarsa** [comment]
I believe the Python upgrade sorted it out for you. That being said the minimum version we need is `3.5` and in fact, CICD tests the binding against that as well. I can't explain how and why this is happening to you but keep in mind that we don't officially support the OS you are using. We only officially support Raspbian (32 and 64 bit).

**Comment by Bazmundi** [comment]
> I believe the Python upgrade sorted it out for you. That being said the minimum version we need is `3.5` and in fact, CICD tests the binding against that as well. I can't explain how and why this is happening to you but keep in mind that we don't officially support the OS you are using. We only officially support Raspbian (32 and 64 bit).

No problem.   I have added "upgrade to python 3.9.2" to the workflow for setting up the devices.  Thanks for the steerage.

**Comment by Bazmundi** [comment]
@creating-worlds 

Hmmm.  Can't help at the moment.  https://github.com/Picovoice/porcupine/issues/653 so I've a few weeks left before I can try again.  But isn't it odd then that it looked like I had sorted my problem by installing 3.9.2 on hypriot, since it wasn't apparently a problem on the Raspian OS.
