### ISSUE TITLE
Nodejs quickstart - Error: Cannot find module '@picovoice/porcupine-node/builtin_keywords'

### ISSUE THREAD

**Issue by MoritzSGit** [Picovoice/porcupine#702]
### What is the URL of the doc?

https://picovoice.ai/docs/quick-start/porcupine-nodejs/

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)

Hello, I followed the quickstart guide for Nodejs on the Raspberry Pi.
I created a folder called `myapp`
Inside this folder I did `npm init`.
Then, I did `npm install @picovoice/porcupine-node`. It created a folder called `node_modules` inside `myapp`.
Then I created a file `index.js` and filled it with the following code, according to the guide:

```
const Porcupine = require("@picovoice/porcupine-node");

const {
  PORCUPINE,
  BUMBLEBEE,
} = require("@picovoice/porcupine-node/builtin_keywords");

const accessKey = "${ACCESS_KEY}"
let porcupine = new Porcupine(
    accessKey,
    [GRASSHOPPER, BUMBLEBEE],
    [0.5, 0.65]
);
```

However, when I run node index.js, I get the following error:

```
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '@picovoice/porcupine-node/builtin_keywords'
Require stack:
- /home/pi/myapp/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/pi/myapp/index.js:8:5)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/pi/myapp/index.js' ]
}

```

Is there anything I can do to resolve this issue? Many thanks in advance!!

**Comment by ksyeo1010** [comment]
The docs are outdated, we will update them soon. for now please try using it as:

```javascript
const {
  Porcupine,
  BuiltinKeyword,
  getBuiltinKeywordPath,
} = require("@picovoice/porcupine-node");

let porcupine = new Porcupine(
  accessKey,
  [getBuiltinKeywordPath(BuiltinKeyword.GRASSHOPPER), getBuiltinKeywordPath(BuiltinKeyword.BUMBLEBEE)],
  [0.5, 0.5]
)
```

**Comment by ErisMik** [comment]
The docs changes are live, so I'm closing the issue. As usual, if you run into any additional problems or documentation issues, please feel free to open another issue.
