### ISSUE TITLE
1 object that is a NoneType

### ISSUE THREAD

**Issue by fredrikj31** [Picovoice/Porcupine#75]
### Error
I tried to first make a wake word. By using your optimizer, and it worked. And then I imported it. But this time it says that a object is a NoneType... I don't know what that means, but I google it and find out it maybe a empty variable. I don't know the cuase of this problem, so hope you guys know it. My code is this: 
```
import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), 'Porcupine/binding/python/'))

from porcupine import Porcupine

library_path = "Porcupine/lib/windows/amd64/libpv_porcupine.dll"
model_file_path = "Porcupine/lib/common/porcupine_params.pv"
keyword_file_paths = ['Porcupine/jarvis_windows.ppn']
sensitivities = [0.5]
handle = Porcupine(library_path, model_file_path, keyword_file_paths=keyword_file_paths, sensitivities=sensitivities)

def get_next_audio_frame():
    pass

while True:
    pcm = get_next_audio_frame()
    keyword_index = handle.process(pcm)
    if keyword_index >= 0:
        # detection event logic/callback
        pass

handle.delete()`

And the error im getting:
`Traceback (most recent call last):
  File "program.py", line 19, in <module>
    keyword_index = handle.process(pcm)
  File "Porcupine/binding/python\porcupine.py", line 154, in process
    status = self.process_func(self._handle, (c_short * len(pcm))(*pcm), byref(result))
TypeError: object of type 'NoneType' has no len()
```

I also gave you guys a picture of my file dir. So you can see where the files is.
![desktop](https://user-images.githubusercontent.com/31306224/44959606-9847e500-aef1-11e8-902e-a87712ae1a29.PNG)

Hope you guys can fix it... Just contact me over this issue, or via my email :)

- Fredrik

**Comment by fredrikj31** [comment]
@oziee How I am getting the audio frame? It says on the website, that you should paste this code into your program. And does not explain why and what does what. I was trying the demo yesterday, and it worked. So it can't be that Im not needed something

**Comment by oziee** [comment]
your code above is calling a function get_next_audio_frame()
this function in your code above returns PASS = NOTHING = NULL
you need to remove the pass and add code that it returns

i have no idea what you tried but if you look at the demo code you can see that functions return items

So you do need something.. its not a problem with porcupine. its a problem with your code.. it is not complete to be a working program

**Comment by kenarsa** [comment]
closing due to inactivity.
