### ISSUE TITLE
Porcupine Issue: Problem with Python demo

### ISSUE THREAD

**Issue by Sid220** [Picovoice/porcupine#750]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
The python demo to run as advertised, looking for porcupine hotword

### Actual behaviour
An error as soon as I start it with `python3 porcupine_demo_mic.py --access_key "[MY_ACCESS_KEY]" --keywords porcupine`
```
Traceback (most recent call last):
  File "/home/ubuntu/SmartDisplayPi/assets/gassist/porcupine/demo/python/porcupine_demo_mic.py", line 83, in run
    porcupine = pvporcupine.create(
TypeError: create() got an unexpected keyword argument 'access_key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/SmartDisplayPi/assets/gassist/porcupine/demo/python/porcupine_demo_mic.py", line 230, in <module>
    main()
  File "/home/ubuntu/SmartDisplayPi/assets/gassist/porcupine/demo/python/porcupine_demo_mic.py", line 219, in main
    PorcupineDemo(
  File "/home/ubuntu/SmartDisplayPi/assets/gassist/porcupine/demo/python/porcupine_demo_mic.py", line 113, in run
    except pvporcupine.PorcupineInvalidArgumentError as e:
AttributeError: module 'pvporcupine' has no attribute 'PorcupineInvalidArgumentError'
```

### Steps to reproduce the behaviour
1. Clone this repo
2. `cd demo/python`
3. `python3 -m pip install pvporcupine pvporcupinedemo pvrecorder`
4. `python3 porcupine_demo_mic.py --access_key "[MY_ACCESS_KEY]" --keywords porcupine`

**Comment by kenarsa** [comment]
```python
pip3 install pvporcupinedemo
porcupine_demo_mic --access_key XXX --keywords alexa
```

worked. My guess is that you have a version mismatch

**Comment by Sid220** [comment]
That worked like a charm, even in the same virtual environment as before, thanks!
