### ISSUE TITLE
Porcupine Issue: ExceptionInInitializerError: null caused by FileSystemNotFoundException

### ISSUE THREAD

**Issue by IndexOutOfMJ** [Picovoice/porcupine#774]
### Expected behaviour

Load wake-word.ppn

### Actual behaviour

`
java.lang.ExceptionInInitializerError: null
	at ai.picovoice.porcupine.Porcupine$Builder.build(Porcupine.java:204) ~[picovoice-java-2.1.3.jar!/:na]
	at net.indexoutofmj.neptune.audio.voice.wakeword.NeptuneVoice.<init>(NeptuneVoice.java:17) ~[classes!/:1.0-SNAPSHOT]
	at net.indexoutofmj.neptune.audio.voice.wakeword.NeptuneVoice$Builder.build(NeptuneVoice.java:58) ~[classes!/:1.0-SNAPSHOT]
	at net.indexoutofmj.neptune.tasks.GuildAudioScheduler.<init>(GuildAudioScheduler.java:51) ~[classes!/:1.0-SNAPSHOT]
	at net.indexoutofmj.neptune.generic.NeptuneGuild.bake(NeptuneGuild.java:147) ~[classes!/:1.0-SNAPSHOT]
	at net.indexoutofmj.neptune.generic.NeptuneGuild.connect(NeptuneGuild.java:132) ~[classes!/:1.0-SNAPSHOT]
	at net.indexoutofmj.neptune.commands.JoinCommand.handle(JoinCommand.java:14) ~[classes!/:1.0-SNAPSHOT]
	at net.indexoutofmj.neptune.generic.CommandManager.onMessageReceived(CommandManager.java:45) ~[classes!/:1.0-SNAPSHOT]
	at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:382) ~[JDA-5.0.0-alpha.18.jar!/:5.0.0-alpha.18]
	at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96) ~[JDA-5.0.0-alpha.18.jar!/:5.0.0-alpha.18]
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88) ~[JDA-5.0.0-alpha.18.jar!/:5.0.0-alpha.18]
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70) ~[JDA-5.0.0-alpha.18.jar!/:5.0.0-alpha.18]
	at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:170) ~[JDA-5.0.0-alpha.18.jar!/:5.0.0-alpha.18]
	at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:133) ~[JDA-5.0.0-alpha.18.jar!/:5.0.0-alpha.18]
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39) ~[JDA-5.0.0-alpha.18.jar!/:5.0.0-alpha.18]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:957) ~[JDA-5.0.0-alpha.18.jar!/:5.0.0-alpha.18]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:843) ~[JDA-5.0.0-alpha.18.jar!/:5.0.0-alpha.18]
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:821) ~[JDA-5.0.0-alpha.18.jar!/:5.0.0-alpha.18]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:996) ~[JDA-5.0.0-alpha.18.jar!/:5.0.0-alpha.18]
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) ~[nv-websocket-client-2.14.jar!/:na]
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) ~[nv-websocket-client-2.14.jar!/:na]
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) ~[nv-websocket-client-2.14.jar!/:na]
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) ~[nv-websocket-client-2.14.jar!/:na]
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[nv-websocket-client-2.14.jar!/:na]
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[nv-websocket-client-2.14.jar!/:na]
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[nv-websocket-client-2.14.jar!/:na]
Caused by: java.nio.file.FileSystemNotFoundException: null
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:156) ~[jdk.zipfs:na]
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:142) ~[jdk.zipfs:na]
	at java.base/java.nio.file.Path.of(Path.java:208) ~[na:na]
	at java.base/java.nio.file.Paths.get(Paths.java:98) ~[na:na]
	at ai.picovoice.porcupine.Utils.getResourceDirectory(Utils.java:58) ~[picovoice-java-2.1.3.jar!/:na]
	at ai.picovoice.porcupine.Utils.<clinit>(Utils.java:39) ~[picovoice-java-2.1.3.jar!/:na]
	... 26 common frames omitted

`

### Steps to reproduce the behaviour

Picovoice Version: picovoice-java 2.1.3

Since i am using the spring framework i run into this problem.

I tried to get the file with `new File("path", "file.ppn").getAbsolutePath();` and it gave me the right path 

Thats my code so far:

`
porcupine = new Porcupine.Builder().setSensitivity(0.7f).setKeywordPath("Path to keyword").setAccessKey(PORCUPINE_ACCESS_TOKEN).build();
`

As i said, it worked well until i migrated to the spring framework for java.

**Comment by ksyeo1010** [comment]
Since we don't use the spring framework and seeing this is a `FileSystemNotFoundException` this might be an issue with your configuration rather than Porcupine. We will keep this issue open to see if others have this issue as well.

**Comment by kenarsa** [comment]
closing due to inactivity
