### ISSUE TITLE
Porcupine Activation Error

### ISSUE THREAD

**Issue by ee21m578** [Picovoice/porcupine#792]
When running the create command for porcupine, I get the below error:
**porcupine = pvporcupine.create(access_key='u.....................=',keywords=['picovoice', 'bumblebee'])**

Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    porcupine = pvporcupine.create(access_key='..............',keywords=['picovoice', 'bumblebee'])
  File "C:\Users\akelkart\AppData\Local\Programs\Python\Python38\lib\site-packages\pvporcupine\_init_.py", line 77, in create
    return Porcupine(
  File "C:\Users\akelkart\AppData\Local\Programs\Python\Python38\lib\site-packages\pvporcupine\porcupine.py", line 158, in _init_
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]()
**pvporcupine.porcupine.PorcupineActivationError**
<img width="780" alt="Capture" src="https://user-images.githubusercontent.com/113116843/192436544-4fb362f3-fdfb-4ea4-bd8b-af54845a16ea.PNG">

**Comment by mrrostam** [comment]
Can you also provide the version of `pvporcupine` installed on your computer?

**Comment by ee21m578** [comment]
pvporcupine in ......\site-packages (2.1.4)

**Comment by mrrostam** [comment]
I cannot reproduce it on my side. Can you confirm that you have access to the internet and there is no firewall blocking it?

**Comment by mrrostam** [comment]
closing due to inactivity. re-open if needed

**Comment by ee21m578** [comment]
Yes, I have internet connectivity. Have checked all possible solutions, but did not work

**Comment by ee21m578** [comment]
Please re-open the issue. The timezone difference causes a delay of some hours

**Comment by ee21m578** [comment]
The issue is with pvcobra as well. There might be something I am missing
![image](https://user-images.githubusercontent.com/113116843/193386606-ad6b0ef5-e12a-4f40-8c21-4fd4048acab1.png)

**Comment by kenarsa** [comment]
1- Are you sure you are inputting your AccessKey correctly? Make sure what is between `""` is 100% correct.
2- Can you try your code on some other computer? 
3- Can you try one of the official demos for porcupine or cobra and see what you get from them?
4- Please provide detailed information about your machine (OS build etc).
5- Please provide detailed information about your network settings. e.g. firewall settings etc.

**Comment by ee21m578** [comment]
1- Are you sure you are inputting your AccessKey correctly? Make sure what is between "" is 100% correct.
==> Yes
2- Can you try your code on some other computer?
==> Not working
3- Can you try one of the official demos for porcupine or cobra and see what you get from them?
==> The demos are not working. Maybe I am inputting in a wrong way
4- Please provide detailed information about your machine (OS build etc).
==> OS Name	Microsoft Windows 10 Enterprise
         Version	        10.0.19042 Build 19042
5- Please provide detailed information about your network settings. e.g. firewall settings etc.
==> Firewall would be ON always since I am using my company's laptop

**Comment by ee21m578** [comment]
let me try on my personal machine once. All devices I have tried are either office machines or connected to office network.

**Comment by ee21m578** [comment]
It is working on a personal machine. But, again unable to 

keyword_path = ['E:/BLASTOISE/PYAUDIO/xyz.ppn']
porcupine = pvporcupine.create(access_key=access_key, keyword_paths=keyword_path)

  _File "E:\BLASTOISE\PYAUDIO\trails_raspberry.py", line 14, in <module>
    porcupine = pvporcupine.create(access_key=access_key, keyword_paths=keyword_path)
  File "C:\Users\akell\AppData\Local\Programs\Python\Python310\lib\site-packages\pvporcupine\_init_.py", line 77, in create
    return Porcupine(
  File "C:\Users\akell\AppData\Local\Programs\Python\Python310\lib\site-packages\pvporcupine\porcupine.py", line 158, in _init_
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]()
pvporcupine.porcupine.PorcupineInvalidArgumentError_

==> The same worked on colab

**Comment by kenarsa** [comment]
progress ...
your work computer firewall or something in your network is causing the issue regarding activation.

the invalid argument is about something in your input arguments is incorrect. I can't tell you what it is cause I don't know what you have on your computer.

**Comment by ee21m578** [comment]
Yes. it is an issue with firewall regarding activation. But even after following the porcupine documentation as is, I get the 'invalid argument error'.

I can't tell you what it is cause I don't know what you have on your computer.
==> Sure. I understand. Let me know if any further info is needed to understand this. All the commands I used are posted above

**Comment by mrrostam** [comment]
The screenshot shows that you are using a keyword (.ppn) generated for Raspberry-pi on a Windows machine. Can you fix this and try again?

**Comment by ee21m578** [comment]
Yes. It indeed works with windows version. Guess, the problem is with my simulation of raspberry pi on windows. 
Thanks a lot for the support.
