### ISSUE TITLE
Porcupine Issue:  wrong ELF class: ELFCLASS64

### ISSUE THREAD

**Issue by mph070770** [Picovoice/porcupine#970]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
trying to run the porcupine_demo_mic on a Rpi 400 with Raspberry Pi OS (Bullseye 2023-05-03)

pi@raspberrypi:~/porcupine $ python --version
Python 3.9.2

pi@raspberrypi:~ $ pip3 install pvporcupine
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pvporcupine
  Downloading pvporcupine-2.2.0-py3-none-any.whl (2.3 MB)
     |████████████████████████████████| 2.3 MB 2.1 MB/s
Installing collected packages: pvporcupine
Successfully installed pvporcupine-2.2.0
pi@raspberrypi:~ $ pip3 install pvporcupinedemo
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pvporcupinedemo
  Downloading pvporcupinedemo-2.2.0-py3-none-any.whl (11 kB)
Requirement already satisfied: pvporcupine==2.2.0 in ./.local/lib/python3.9/site-packages (from pvporcupinedemo) (2.2.0)Collecting pvrecorder==1.1.1
  Downloading pvrecorder-1.1.1-py3-none-any.whl (3.8 MB)
     |████████████████████████████████| 3.8 MB 3.2 MB/s
Installing collected packages: pvrecorder, pvporcupinedemo
  WARNING: The scripts porcupine_demo_file and porcupine_demo_mic are installed in '/home/pi/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pvporcupinedemo-2.2.0 pvrecorder-1.1.1

pi@raspberrypi:~/.local/bin $ mkdir /home/pi/porcupine
pi@raspberrypi:~/.local/bin $ cp * /home/pi/porcupine/

### Actual behaviour
pi@raspberrypi:~/porcupine $ ./porcupine_demo_mic --help
Traceback (most recent call last):
  File "/home/pi/porcupine/./porcupine_demo_mic", line 5, in <module>
    from pvporcupinedemo.porcupine_demo_mic import main
  File "/home/pi/.local/lib/python3.9/site-packages/pvporcupinedemo/porcupine_demo_mic.py", line 19, in <module>
    from pvrecorder import PvRecorder
  File "/home/pi/.local/lib/python3.9/site-packages/pvrecorder/__init__.py", line 12, in <module>
    from .pvrecorder import PvRecorder
  File "/home/pi/.local/lib/python3.9/site-packages/pvrecorder/pvrecorder.py", line 20, in <module>
    class PvRecorder(object):
  File "/home/pi/.local/lib/python3.9/site-packages/pvrecorder/pvrecorder.py", line 203, in PvRecorder
    _LIBRARY = cdll.LoadLibrary(_lib_path.__func__())
  File "/usr/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/pi/.local/lib/python3.9/site-packages/pvrecorder/lib/raspberry-pi/cortex-a72-aarch64/libpv_recorder.so: wrong ELF class: ELFCLASS64

**Comment by mph070770** [comment]
Ah - so you need a 64bit version of Pi OS.
