### ISSUE TITLE
Porcupine Issue: SyntaxError when importing pvporcupine

### ISSUE THREAD

**Issue by icamelot** [Picovoice/porcupine#973]
Traceback (most recent call last):
  File "/home/user/lab/run.py", line 4, in <module>
    import pvporcupine
  File "/usr/local/lib/python3.7/dist-packages/pvporcupine/__init__.py", line 12, in <module>
    from ._factory import *
  File "/usr/local/lib/python3.7/dist-packages/pvporcupine/_factory.py", line 24
    library_path: Optional[str] = None,
                       ^
SyntaxError: invalid syntax

**Comment by icamelot** [comment]
Sorry , I used python2 running it
