### ISSUE TITLE
Porcupine Issue: 

### ISSUE THREAD

**Issue by Immortalswordsman** [Picovoice/porcupine#995]
Traceback (most recent call last):
  File "D:\Python10\Orator-main\speechmodules\wakeword.py", line 34, in <module>
    picowakeword = PicoWakeWord(PICOVOICE_API_KEY, keyword_path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python10\Orator-main\speechmodules\wakeword.py", line 12, in __init__
    self.porcupine = pvporcupine.create(
                     ^^^^^^^^^^^^^^^^^^^
  File "D:\Python311\Lib\site-packages\pvporcupine\__init__.py", line 77, in create
    return Porcupine(
           ^^^^^^^^^^
  File "D:\Python311\Lib\site-packages\pvporcupine\porcupine.py", line 158, in __init__
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]()
pvporcupine.porcupine.PorcupineActivationLimitError

Process finished with exit code 1
Environment widows11, Python 11 reported an error

**Comment by kenarsa** [comment]
How is this a `bug`?
